# Data Frame

## Introduction

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

%matplotlib inline

In [3]:
pd.read_csv('./course-files/course-sources/Mcdonalds.csv')

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),10.1 oz (285 g),510,150,17.0,26,9.0,44,0.5,...,80,27,1,4,64,12,15,0,40,8
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),13.4 oz (381 g),690,200,23.0,35,12.0,58,1.0,...,106,35,1,5,85,15,20,0,50,10
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),6.7 oz (190 g),340,100,11.0,17,6.0,29,0.0,...,53,18,1,2,43,8,10,0,25,6
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810,290,32.0,50,15.0,76,1.0,...,114,38,2,9,103,21,20,0,60,6
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),7.1 oz (202 g),410,150,16.0,25,8.0,38,0.0,...,57,19,1,5,51,10,10,0,30,4

In [4]:
mc = pd.read_csv('./course-files/course-sources/Mcdonalds.csv')

In [5]:
mc.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [6]:
mc.tail()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),10.1 oz (285 g),510,150,17.0,26,9.0,44,0.5,...,80,27,1,4,64,12,15,0,40,8
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),13.4 oz (381 g),690,200,23.0,35,12.0,58,1.0,...,106,35,1,5,85,15,20,0,50,10
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),6.7 oz (190 g),340,100,11.0,17,6.0,29,0.0,...,53,18,1,2,43,8,10,0,25,6
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810,290,32.0,50,15.0,76,1.0,...,114,38,2,9,103,21,20,0,60,6
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),7.1 oz (202 g),410,150,16.0,25,8.0,38,0.0,...,57,19,1,5,51,10,10,0,30,4

In [7]:
mc_selected = pd.read_csv('./course-files/course-sources/Mcdonalds.csv',
                         usecols=['Item','Serving Size', 'Calories', 'Calories from Fat', 'TotalFat'])
mc_selected.head()

,Item,Serving Size,Calories,Calories from Fat,TotalFat
0,Egg McMuffin,4.8 oz (136 g),300,120,13.0
1,Egg White Delight,4.8 oz (135 g),250,70,8.0
2,Sausage McMuffin,3.9 oz (111 g),370,200,23.0
3,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0
4,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0

In [8]:
mc_selected = pd.read_csv('./course-files/course-sources/Mcdonalds.csv',
                         usecols=['Item','Serving Size', 'Calories', 'Calories from Fat', 'TotalFat'],
                         index_col='Item')
mc_selected.head()

,Serving Size,Calories,Calories from Fat,TotalFat
Item,,,,
Egg McMuffin,4.8 oz (136 g),300,120,13.0
Egg White Delight,4.8 oz (135 g),250,70,8.0
Sausage McMuffin,3.9 oz (111 g),370,200,23.0
Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0
Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0

## Methods and atributes of Data Frame

In [9]:
mcframe = pd.read_csv('./course-files/course-sources/Mcdonalds.csv')
mcseries = pd.read_csv('./course-files/course-sources/Mcdonalds.csv',
                      usecols=['Item', 'Calories'],
                      index_col='Item',
                      squeeze=True)
print(type(mcframe))
print(type(mcseries))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [10]:
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [11]:
mcseries.head()

Item
Egg McMuffin                        300
Egg White Delight                   250
Sausage McMuffin                    370
Sausage McMuffin with Egg           450
Sausage McMuffin with Egg Whites    400
Name: Calories, dtype: int64

In [12]:
mcseries.count()

260

In [15]:
mcframe.count()  # not NaN

Category                         260
Item                             260
Serving Size                     260
Calories                         260
Calories from Fat                260
TotalFat                         260
Total Fat (% Daily Value)        260
Saturated Fat                    260
Saturated Fat (% Daily Value)    260
Trans Fat                        260
Cholesterol                      260
Cholesterol (% Daily Value)      260
Sodium                           260
Sodium (% Daily Value)           260
Carbohydrates                    260
Carbohydrates (% Daily Value)    260
Dietary Fiber                    260
Dietary Fiber (% Daily Value)    260
Sugars                           260
Protein                          260
Vitamin A (% Daily Value)        260
Vitamin C (% Daily Value)        260
Calcium (% Daily Value)          260
Iron (% Daily Value)             260
dtype: int64

In [16]:
mcframe.size

6240

In [17]:
len(mcframe)

260

In [18]:
len(mcseries)

260

In [19]:
mcseries.dtypes

dtype('int64')

In [20]:
mcframe.dtypes

Category                          object
Item                              object
Serving Size                      object
Calories                           int64
Calories from Fat                  int64
TotalFat                         float64
Total Fat (% Daily Value)          int64
Saturated Fat                    float64
Saturated Fat (% Daily Value)      int64
Trans Fat                        float64
Cholesterol                        int64
Cholesterol (% Daily Value)        int64
Sodium                             int64
Sodium (% Daily Value)             int64
Carbohydrates                      int64
Carbohydrates (% Daily Value)      int64
Dietary Fiber                      int64
Dietary Fiber (% Daily Value)      int64
Sugars                             int64
Protein                            int64
Vitamin A (% Daily Value)          int64
Vitamin C (% Daily Value)          int64
Calcium (% Daily Value)            int64
Iron (% Daily Value)               int64
dtype: object

In [39]:
mcseries.dtypes.type

numpy.int64

### frame.dtypes.value_counts() - grouped and sorted types in frame

In [40]:
mcframe.dtypes.value_counts()

int64      18
float64     3
object      3
dtype: int64

In [41]:
mcseries.shape

(260,)

In [42]:
mcframe.shape  # (rows, columns)

(260, 24)

In [43]:
mcseries.axes  # [osie]

[Index(['Egg McMuffin', 'Egg White Delight', 'Sausage McMuffin',
        'Sausage McMuffin with Egg', 'Sausage McMuffin with Egg Whites',
        'Steak & Egg McMuffin', 'Bacon, Egg & Cheese Biscuit (Regular Biscuit)',
        'Bacon, Egg & Cheese Biscuit (Large Biscuit)',
        'Bacon, Egg & Cheese Biscuit with Egg Whites (Regular Biscuit)',
        'Bacon, Egg & Cheese Biscuit with Egg Whites (Large Biscuit)',
        ...
        'Shamrock Shake (Medium)', 'Shamrock Shake (Large)',
        'McFlurry with M&M’s Candies (Small)',
        'McFlurry with M&M’s Candies (Medium)',
        'McFlurry with M&M’s Candies (Snack)',
        'McFlurry with Oreo Cookies (Small)',
        'McFlurry with Oreo Cookies (Medium)',
        'McFlurry with Oreo Cookies (Snack)',
        'McFlurry with Reese's Peanut Butter Cups (Medium)',
        'McFlurry with Reese's Peanut Butter Cups (Snack)'],
       dtype='object', name='Item', length=260)]

In [44]:
mcframe.axes

[RangeIndex(start=0, stop=260, step=1),
 Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
        'TotalFat', 'Total Fat (% Daily Value)', 'Saturated Fat',
        'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
        'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
        'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
        'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
        'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
        'Calcium (% Daily Value)', 'Iron (% Daily Value)'],
       dtype='object')]

In [45]:
mcseries.index

Index(['Egg McMuffin', 'Egg White Delight', 'Sausage McMuffin',
       'Sausage McMuffin with Egg', 'Sausage McMuffin with Egg Whites',
       'Steak & Egg McMuffin', 'Bacon, Egg & Cheese Biscuit (Regular Biscuit)',
       'Bacon, Egg & Cheese Biscuit (Large Biscuit)',
       'Bacon, Egg & Cheese Biscuit with Egg Whites (Regular Biscuit)',
       'Bacon, Egg & Cheese Biscuit with Egg Whites (Large Biscuit)',
       ...
       'Shamrock Shake (Medium)', 'Shamrock Shake (Large)',
       'McFlurry with M&M’s Candies (Small)',
       'McFlurry with M&M’s Candies (Medium)',
       'McFlurry with M&M’s Candies (Snack)',
       'McFlurry with Oreo Cookies (Small)',
       'McFlurry with Oreo Cookies (Medium)',
       'McFlurry with Oreo Cookies (Snack)',
       'McFlurry with Reese's Peanut Butter Cups (Medium)',
       'McFlurry with Reese's Peanut Butter Cups (Snack)'],
      dtype='object', name='Item', length=260)

In [46]:
mcframe.index

RangeIndex(start=0, stop=260, step=1)

In [48]:
# mcseries.columns  # error, because Series doesn't have columns atr
mcframe.columns

Index(['Category', 'Item', 'Serving Size', 'Calories', 'Calories from Fat',
       'TotalFat', 'Total Fat (% Daily Value)', 'Saturated Fat',
       'Saturated Fat (% Daily Value)', 'Trans Fat', 'Cholesterol',
       'Cholesterol (% Daily Value)', 'Sodium', 'Sodium (% Daily Value)',
       'Carbohydrates', 'Carbohydrates (% Daily Value)', 'Dietary Fiber',
       'Dietary Fiber (% Daily Value)', 'Sugars', 'Protein',
       'Vitamin A (% Daily Value)', 'Vitamin C (% Daily Value)',
       'Calcium (% Daily Value)', 'Iron (% Daily Value)'],
      dtype='object')

In [49]:
mcseries.values

array([ 300,  250,  370,  450,  400,  430,  460,  520,  410,  470,  430,
        480,  510,  570,  460,  520,  410,  470,  540,  460,  400,  420,
        550,  500,  620,  570,  670,  740,  800,  640,  690, 1090, 1150,
        990, 1050,  350,  520,  300,  150,  460,  290,  260,  530,  520,
        600,  610,  540,  750,  240,  290,  430,  720,  380,  440,  430,
        430,  500,  510,  350,  670,  510,  610,  450,  750,  590,  430,
        360,  480,  430,  360,  630,  480,  610,  450,  670,  520,  540,
        380,  190,  280,  470,  940, 1880,  390,  140,  380,  220,  140,
        450,  290,  340,  260,  330,  250,  360,  280,  230,  340,  510,
        110,   20,   15,  150,  250,  160,  150,   45,  330,  340,  280,
        140,  200,  280,  100,    0,    0,    0,    0,  140,  190,  270,
        100,    0,    0,    0,    0,  140,  200,  280,  100,  100,  130,
         80,  150,  190,  280,    0,    0,    0,    0,    0,  150,  180,
        220,  110,    0,    0,    0,  170,  210,  280,  270,  340,  430,
        270,  330,  430,  260,  330,  420,  210,  260,  330,  100,  130,
        170,  200,  250,  310,  200,  250,  310,  190,  240,  300,  140,
        170,  220,  340,  410,  500,  270,  330,  390,  320,  390,  480,
        250,  310,  370,  360,  440,  540,  280,  340,  400,  140,  190,
        270,  130,  180,  260,  130,  180,  250,  120,  170,  240,   80,
        120,  160,  290,  350,  480,  240,  290,  390,  280,  340,  460,
        230,  270,  370,  450,  550,  670,  450,  550,  670,  530,  630,
        760,  220,  260,  340,  210,  250,  330,  210,  260,  340,  530,
        660,  820,  550,  690,  850,  560,  700,  850,  660,  820,  650,
        930,  430,  510,  690,  340,  810,  410], dtype=int64)

In [53]:
mcframe.values  # list of lists. Each list inside is an row from DFrame

array([['Breakfast', 'Egg McMuffin', '4.8 oz (136 g)', ..., 0, 25, 15],
       ['Breakfast', 'Egg White Delight', '4.8 oz (135 g)', ..., 0, 25,
        8],
       ['Breakfast', 'Sausage McMuffin', '3.9 oz (111 g)', ..., 0, 25,
        10],
       ...,
       ['Smoothies & Shakes', 'McFlurry with Oreo Cookies (Snack)',
        '6.7 oz (190 g)', ..., 0, 25, 6],
       ['Smoothies & Shakes',
        "McFlurry with Reese's Peanut Butter Cups (Medium)",
        '14.2 oz (403 g)', ..., 0, 60, 6],
       ['Smoothies & Shakes',
        "McFlurry with Reese's Peanut Butter Cups (Snack)",
        '7.1 oz (202 g)', ..., 0, 30, 4]], dtype=object)

In [54]:
# mcseries.info()  # error, because Series doesn't have columns atr
mcframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Category                       260 non-null    object
 1   Item                           260 non-null    object
 2   Serving Size                   260 non-null    object
 3   Calories                       260 non-null    int64
 4   Calories from Fat              260 non-null    int64
 5   TotalFat                       260 non-null    float64
 6   Total Fat (% Daily Value)      260 non-null    int64
 7   Saturated Fat                  260 non-null    float64
 8   Saturated Fat (% Daily Value)  260 non-null    int64
 9   Trans Fat                      260 non-null    float64
 10  Cholesterol                    260 non-null    int64
 11  Cholesterol (% Daily Value)    260 non-null    int64
 12  Sodium                         260 non-null    int64
 13  Sodium (% Daily Value)         260 non-null    int64
 14  Carbohydrates                  260 non-null    int64
 15  Carbohydrates (% Daily Value)  260 non-null    int64
 16  Dietary Fiber                  260 non-null    int64
 17  Dietary Fiber (% Daily Value)  260 non-null    int64
 18  Sugars                         260 non-null    int64
 19  Protein                        260 non-null    int64
 20  Vitamin A (% Daily Value)      260 non-null    int64
 21  Vitamin C (% Daily Value)      260 non-null    int64
 22  Calcium (% Daily Value)        260 non-null    int64
 23  Iron (% Daily Value)           260 non-null    int64
dtypes: float64(3), int64(18), object(3)
memory usage: 48.9+ KB

In [55]:
mcseries.value_counts()

0       16
430     10
340     10
280      9
250      8
        ..
620      1
650      1
640      1
1150     1
740      1
Name: Calories, Length: 78, dtype: int64

In [59]:
mcframe.value_counts()
# if in dataset are 2 or more same rows it will show the info

Category        Item                                Serving Size     Calories  Calories from Fat  TotalFat  Total Fat (% Daily Value)  Saturated Fat  Saturated Fat (% Daily Value)  Trans Fat  Cholesterol  Cholesterol (% Daily Value)  Sodium  Sodium (% Daily Value)  Carbohydrates  Carbohydrates (% Daily Value)  Dietary Fiber  Dietary Fiber (% Daily Value)  Sugars  Protein  Vitamin A (% Daily Value)  Vitamin C (% Daily Value)  Calcium (% Daily Value)  Iron (% Daily Value)
Beef & Pork     Bacon Clubhouse Burger              9.5 oz (270 g)   720       360                40.0      62                         15.0           75                             1.5        115          38                           1470    61                      51             17                             4              14                             14      39       8                          25                         30                       25                      1
Coffee & Tea    Iced Nonfat Caramel Mocha (Medium)  16 fl oz cup     270       45                 5.0       8                          3.0            16                             0.0        20           7                            170     7                       47             16                             1              2                              41      10       15                         0                          30                       2                       1
                Iced Tea (Child)                    12 fl oz cup     0         0                  0.0       0                          0.0            0                              0.0        0            0                            5       0                       0              0                              0              0                              0       0        0                          0                          0                        0                       1
                Iced Tea (Large)                    30 fl oz cup     0         0                  0.0       0                          0.0            0                              0.0        0            0                            15      1                       0              0                              0              0                              0       0        0                          0                          0                        0                       1
                Iced Tea (Medium)                   21 fl oz cup     0         0                  0.0       0                          0.0            0                              0.0        0            0                            10      0                       0              0                              0              0                              0       0        0                          0                          0                        0                       1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ..
Chicken & Fish  Chicken McNuggets (4 piece)         2.3 oz (65 g)    190       110                12.0      18                         2.0            10                             0.0        25           9                            360     15                      12             4                              1              2                              0       9        0                          2                          0                        2                       1
                Chicken McNuggets (40 piece)        22.8 oz (646 g)  1880      1060               118.0     182                        20.0           101                            1.0        265          89                           3600    150                     118            39                             6              24                             1       87       0                          15                         8                        25                      1
                Chicken McNuggets (6 piece)         3.4 oz (97 g)    280       160                18.0      27                         3.0            15                             0.0        40           13                           540     22                      18             6                              1              4                              0       13       0                          2                          2                        4                       1
                Filet-O-Fish                        5 oz (142 g)     390       170                19.0      29                         4.0            19                             0.0        40           14                           590     24                      39             13                             2              7                              5       15       2                          0                          15                       10                      1
Snacks & Sides  Small French Fries                  2.6 oz (75 g)    230       100                11.0      17                         1.5            8                              0.0        0            0                            130     5                       30             10                             2              10                             0       2        0                          30                         0                        4                       1
Length: 260, dtype: int64

In [58]:
mcframe['Calories'].value_counts()

0       16
430     10
340     10
280      9
250      8
        ..
620      1
650      1
640      1
1150     1
740      1
Name: Calories, Length: 78, dtype: int64

In [60]:
mcframe['Category'].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Beverages             27
Chicken & Fish        27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

In [64]:
mcseries.sample()  # returns random value from a Series or Frame

Item
Premium McWrap Chicken Sweet Chili (Grilled Chicken)    380
Name: Calories, dtype: int64

In [67]:
mcframe.sample(n=3)  # 3 samples

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
189,Coffee & Tea,Nonfat Caramel Mocha (Large),20 fl oz cup,370,35,3.5,6,2.5,11,0.0,...,67,22,1,5,61,17,20,0,50,4
55,Beef & Pork,Jalapeño Double,5.6 oz (159 g),430,210,23.0,36,9.0,44,1.0,...,35,12,2,7,6,22,6,8,20,20
79,Chicken & Fish,Chicken McNuggets (6 piece),3.4 oz (97 g),280,160,18.0,27,3.0,15,0.0,...,18,6,1,4,0,13,0,2,2,4

In [70]:
mcframe.sample(n=3, axis='columns')  # 3 sample columns

     Carbohydrates (% Daily Value)  TotalFat  Vitamin C (% Daily Value)
0                               10      13.0                          0
1                               10       8.0                          0
2                               10      23.0                          0
3                               10      28.0                          0
4                               10      23.0                          0
..                             ...       ...                        ...
255                             27      17.0                          0
256                             35      23.0                          0
257                             18      11.0                          0
258                             38      32.0                          0
259                             19      16.0                          0

[260 rows x 3 columns]

In [72]:
# how many percent % do you want see?
mcframe.sample(frac=.02)  # .02 or 0.02 == 2%

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
14,Breakfast,Sausage Biscuit with Egg Whites (Regular Biscuit),5.9 oz (167 g),460,250,27.0,42,12.0,62,0.0,...,34,11,2,6,3,18,0,0,8,15
205,Coffee & Tea,French Vanilla Iced Coffee (Small),16 fl oz cup,120,40,4.5,7,3.0,15,0.0,...,20,7,0,0,19,1,4,0,4,0
189,Coffee & Tea,Nonfat Caramel Mocha (Large),20 fl oz cup,370,35,3.5,6,2.5,11,0.0,...,67,22,1,5,61,17,20,0,50,4
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),7.1 oz (202 g),410,150,16.0,25,8.0,38,0.0,...,57,19,1,5,51,10,10,0,30,4
19,Breakfast,"Bacon, Egg & Cheese McGriddles",6.1 oz (174 g),460,190,21.0,32,9.0,44,0.0,...,48,16,2,9,15,19,10,10,20,15

## Download data from Data Frame

In [73]:
mcframe.Calories  # a column like an atribute

0      300
1      250
2      370
3      450
4      400
      ...
255    510
256    690
257    340
258    810
259    410
Name: Calories, Length: 260, dtype: int64

In [74]:
type(mcframe.Calories)

pandas.core.series.Series

In [75]:
mcframe.Calories.mean()

368.2692307692308

In [76]:
mcframe.Calories.median()

340.0

In [86]:
print(
    mcframe.Calories.loc[mcframe.Calories.idxmax()]
)
mcframe.Calories.max()

1880

1880

In [78]:
mcframe.Calories.idxmax()

82

In [83]:
mcframe.Item[82]

'Chicken McNuggets (40 piece)'

In [84]:
mcframe.Item[mcframe.Calories.idxmax()]

'Chicken McNuggets (40 piece)'

In [87]:
all(mcframe['Calories'].head() == mcframe.Calories.head())

True

In [88]:
mcframe['Item'][82]

'Chicken McNuggets (40 piece)'

In [89]:
mcframe['Item'].loc[82]

'Chicken McNuggets (40 piece)'

In [90]:
mcframe['Item'].iloc[82]

'Chicken McNuggets (40 piece)'

In [93]:
mcframe.loc[82]  # a whole row in a Series object

Category                                       Chicken & Fish
Item                             Chicken McNuggets (40 piece)
Serving Size                                  22.8 oz (646 g)
Calories                                                 1880
Calories from Fat                                        1060
TotalFat                                                118.0
Total Fat (% Daily Value)                                 182
Saturated Fat                                            20.0
Saturated Fat (% Daily Value)                             101
Trans Fat                                                 1.0
Cholesterol                                               265
Cholesterol (% Daily Value)                                89
Sodium                                                   3600
Sodium (% Daily Value)                                    150
Carbohydrates                                             118
Carbohydrates (% Daily Value)                              39
Dietary Fiber                                               6
Dietary Fiber (% Daily Value)                              24
Sugars                                                      1
Protein                                                    87
Vitamin A (% Daily Value)                                   0
Vitamin C (% Daily Value)                                  15
Calcium (% Daily Value)                                     8
Iron (% Daily Value)                                       25
Name: 82, dtype: object

In [94]:
mcframe.loc[82].loc['Item']

'Chicken McNuggets (40 piece)'

In [95]:
mcframe.loc[80:85]

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
80,Chicken & Fish,Chicken McNuggets (10 piece),5.7 oz (162 g),470,270,30.0,45,5.0,25,0.0,...,30,10,2,6,0,22,0,4,2,6
81,Chicken & Fish,Chicken McNuggets (20 piece),11.4 oz (323 g),940,530,59.0,91,10.0,50,0.0,...,59,20,3,12,0,44,0,8,4,10
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,1060,118.0,182,20.0,101,1.0,...,118,39,6,24,1,87,0,15,8,25
83,Chicken & Fish,Filet-O-Fish,5 oz (142 g),390,170,19.0,29,4.0,19,0.0,...,39,13,2,7,5,15,2,0,15,10
84,Salads,Premium Bacon Ranch Salad (without Chicken),7.9 oz (223 g),140,70,7.0,11,3.5,18,0.0,...,10,3,3,12,4,9,170,30,15,6
85,Salads,Premium Bacon Ranch Salad with Crispy Chicken,9 oz (255 g),380,190,21.0,33,6.0,29,0.0,...,22,7,2,10,5,25,100,25,15,8

In [105]:
mcframe.loc[82].loc['Item':'Calories']  # 3 columns of 82'nd row

Item            Chicken McNuggets (40 piece)
Serving Size                 22.8 oz (646 g)
Calories                                1880
Name: 82, dtype: object

In [115]:
mcframe.loc[80:85].loc['Item':'Calories']  # why 0 row?

Empty DataFrame
Columns: [Category, Item, Serving Size, Calories, Calories from Fat, TotalFat, Total Fat (% Daily Value), Saturated Fat, Saturated Fat (% Daily Value), Trans Fat, Cholesterol, Cholesterol (% Daily Value), Sodium, Sodium (% Daily Value), Carbohydrates, Carbohydrates (% Daily Value), Dietary Fiber, Dietary Fiber (% Daily Value), Sugars, Protein, Vitamin A (% Daily Value), Vitamin C (% Daily Value), Calcium (% Daily Value), Iron (% Daily Value)]
Index: []

[0 rows x 24 columns]

In [107]:
mcframe.loc[80:86:2]  # get every 2nd row from 80 to 86

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
80,Chicken & Fish,Chicken McNuggets (10 piece),5.7 oz (162 g),470,270,30.0,45,5.0,25,0.0,...,30,10,2,6,0,22,0,4,2,6
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,1060,118.0,182,20.0,101,1.0,...,118,39,6,24,1,87,0,15,8,25
84,Salads,Premium Bacon Ranch Salad (without Chicken),7.9 oz (223 g),140,70,7.0,11,3.5,18,0.0,...,10,3,3,12,4,9,170,30,15,6
86,Salads,Premium Bacon Ranch Salad with Grilled Chicken,8.5 oz (241 g),220,80,8.0,13,4.0,20,0.0,...,8,3,2,10,4,29,110,30,15,8

In [125]:
                #idx, column
print(mcframe.loc[82, 'Item'])
# print(mcframe.loc['Item', 82])  # error

Chicken McNuggets (40 piece)

In [123]:
# mcframe['Item':'Calories']  # error
# mcframe[['Item':'Calories']]  # error
mcframe[['Item','Calories', 'Sugars']].head()

                               Item  Calories  Sugars
0                      Egg McMuffin       300       3
1                 Egg White Delight       250       3
2                  Sausage McMuffin       370       2
3         Sausage McMuffin with Egg       450       2
4  Sausage McMuffin with Egg Whites       400       2

## Columns' adding and deleting

In [129]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Sugars', 'Protein', 'Cholesterol']
)
mcframe.head()

,Category,Item,Calories,TotalFat,Cholesterol,Sugars,Protein
0,Breakfast,Egg McMuffin,300,13.0,260,3,17
1,Breakfast,Egg White Delight,250,8.0,25,3,18
2,Breakfast,Sausage McMuffin,370,23.0,45,2,14
3,Breakfast,Sausage McMuffin with Egg,450,28.0,285,2,21
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0,50,2,21

In [130]:
mcframe.TotalFat.head()

0    13.0
1     8.0
2    23.0
3    28.0
4    23.0
Name: TotalFat, dtype: float64

In [133]:
SugarAndFat = mcframe.Sugars + mcframe.TotalFat
SugarAndFat.head()

0    16.0
1    11.0
2    25.0
3    30.0
4    25.0
dtype: float64

### Adding a column

In [135]:
mcframe['SugarAndFat'] = SugarAndFat
mcframe.head()

,Category,Item,Calories,TotalFat,Cholesterol,Sugars,Protein,SugarAndFat
0,Breakfast,Egg McMuffin,300,13.0,260,3,17,16.0
1,Breakfast,Egg White Delight,250,8.0,25,3,18,11.0
2,Breakfast,Sausage McMuffin,370,23.0,45,2,14,25.0
3,Breakfast,Sausage McMuffin with Egg,450,28.0,285,2,21,30.0
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0,50,2,21,25.0

### Adding a column in a custom place in DFrame

In [137]:
mcframe.insert(
    loc=2,  # a place of columns from 0
    column='SPF',  # a name of column
    value=mcframe.Sugars + mcframe.Protein + mcframe.TotalFat
)
mcframe.head()

,Category,Item,SPF,Calories,TotalFat,Cholesterol,Sugars,Protein,SugarAndFat
0,Breakfast,Egg McMuffin,33.0,300,13.0,260,3,17,16.0
1,Breakfast,Egg White Delight,29.0,250,8.0,25,3,18,11.0
2,Breakfast,Sausage McMuffin,39.0,370,23.0,45,2,14,25.0
3,Breakfast,Sausage McMuffin with Egg,51.0,450,28.0,285,2,21,30.0
4,Breakfast,Sausage McMuffin with Egg Whites,46.0,400,23.0,50,2,21,25.0

### Deleting a column

In [139]:
# del mcframe.SPF  # error
del mcframe['SPF']
mcframe.head()

,Category,Item,Calories,TotalFat,Cholesterol,Sugars,Protein,SugarAndFat
0,Breakfast,Egg McMuffin,300,13.0,260,3,17,16.0
1,Breakfast,Egg White Delight,250,8.0,25,3,18,11.0
2,Breakfast,Sausage McMuffin,370,23.0,45,2,14,25.0
3,Breakfast,Sausage McMuffin with Egg,450,28.0,285,2,21,30.0
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0,50,2,21,25.0

In [141]:
mcframe.drop(columns=['SugarAndFat']).head()

,Category,Item,Calories,TotalFat,Cholesterol,Sugars,Protein
0,Breakfast,Egg McMuffin,300,13.0,260,3,17
1,Breakfast,Egg White Delight,250,8.0,25,3,18
2,Breakfast,Sausage McMuffin,370,23.0,45,2,14
3,Breakfast,Sausage McMuffin with Egg,450,28.0,285,2,21
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0,50,2,21

In [143]:
mcframe['SugarAndFat']
# mcframe.drop(columns=['SugarAndFat'], inplace=True)  # del and save

0       16.0
1       11.0
2       25.0
3       30.0
4       25.0
       ...
255     81.0
256    108.0
257     54.0
258    135.0
259     67.0
Name: SugarAndFat, Length: 260, dtype: float64

#### Deleting by labels & axis

If we use labels, we should use axis to declare which axe we want delete: verctical or horizontal.

Horizontal (rows): `axis=0`<br/>
Vertical (columns): `axis=1`

It is possibility to deleting both columns and rows.

In [146]:
mcframe.head()

,Category,Item,Calories,TotalFat,Cholesterol,Sugars,Protein,SugarAndFat
0,Breakfast,Egg McMuffin,300,13.0,260,3,17,16.0
1,Breakfast,Egg White Delight,250,8.0,25,3,18,11.0
2,Breakfast,Sausage McMuffin,370,23.0,45,2,14,25.0
3,Breakfast,Sausage McMuffin with Egg,450,28.0,285,2,21,30.0
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0,50,2,21,25.0

In [147]:
mcframe.drop(labels=['SugarAndFat'], axis=1).head()  # inplace is available

,Category,Item,Calories,TotalFat,Cholesterol,Sugars,Protein
0,Breakfast,Egg McMuffin,300,13.0,260,3,17
1,Breakfast,Egg White Delight,250,8.0,25,3,18
2,Breakfast,Sausage McMuffin,370,23.0,45,2,14
3,Breakfast,Sausage McMuffin with Egg,450,28.0,285,2,21
4,Breakfast,Sausage McMuffin with Egg Whites,400,23.0,50,2,21

## Cleaning data

If some data is missing we may use a few ways:
* update null to average
* deleting each row
* deleting null value from row

Parameters of `frame.dropna()`:
* `how='any'`/`'all'`, default any
* `subset=['cols_name', ...]`, default None
* `axis=0`/`1` or `axis='rows'`/`'columns'`, default 0
* `inplace=True`, default False

In [149]:
mcframe = pd.read_csv('./course-files/course-sources/Mcdonalds.csv')
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [151]:
mcframe.loc[1, 'Calories'] = np.NaN
mcframe.loc[2, 'TotalFat'] = np.NaN
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),NaN,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370.0,200,NaN,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [153]:
mcframe.dropna().head()  # delete each row !!!

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,230,26.0,40,13.0,65,0.0,...,38,13,2,7,3,19,10,8,15,15

In [154]:
mcframe.dropna(how='all').head()  # all vals in row are null

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),NaN,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370.0,200,NaN,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [155]:
mcframe.dropna(subset=['TotalFat'], how='any').head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),NaN,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20

In [156]:
mcframe.dropna(subset=['Calories'], how='any').head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370.0,200,NaN,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20

In [157]:
mcframe.dropna(subset=['TotalFat', 'Calories'], how='any').head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,230,26.0,40,13.0,65,0.0,...,38,13,2,7,3,19,10,8,15,15

### axis [oś] in dropna

In default `axis=0`. It is equal to `axis='rows'`.<br/>
`axis=1` equals to `axis='columns'`

In [160]:
mcframe.dropna(axis='rows').head()  # like default `axis=0`

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,230,26.0,40,13.0,65,0.0,...,38,13,2,7,3,19,10,8,15,15

In [162]:
mcframe.dropna(axis='columns').head()  # deleted cols Calories & TotFat

,Category,Item,Serving Size,Calories from Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,Cholesterol,Cholesterol (% Daily Value),...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),120,20,5.0,25,0.0,260,87,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),70,12,3.0,15,0.0,25,8,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),200,35,8.0,42,0.0,45,15,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),250,43,10.0,52,0.0,285,95,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),210,35,8.0,42,0.0,50,16,...,30,10,4,17,2,21,6,0,25,10

## Data cleaning - fillna

In [2]:
mcframe = pd.read_csv('./course-files/course-sources/Mcdonalds.csv')
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [6]:
mcframe.loc[1, 'TotalFat'] = np.NaN
mcframe.loc[1, 'Saturated Fat'] = np.NaN
mcframe.loc[2, 'Saturated Fat'] = np.NaN
mcframe.loc[3, 'Category'] = np.NaN
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,NaN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [8]:
mcframe.fillna(value=0).head()  # category was changed to 0

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,0.0,12,0.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,0.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,0,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

### Using a dict with mapping NaN or null values

In [13]:
replace_definition_table = {'Category': 'UNKNOWN', 'TotalFat': 0, 'Saturated Fat': 0}
replace_definition_table

{'Category': 'UNKNOWN', 'TotalFat': 0, 'Saturated Fat': 0}

In [14]:
mcframe.fillna(value=replace_definition_table).head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,0.0,12,0.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,0.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,UNKNOWN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [16]:
# clean data in a required column and we save it
mcframe['Category'].fillna(value='UNKNOWN', inplace=True)
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,UNKNOWN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

### Average in cleaning

In [17]:
mcframe.loc[1, 'TotalFat'] = np.NaN
mcframe.loc[1, 'Saturated Fat'] = np.NaN
mcframe.loc[2, 'Saturated Fat'] = np.NaN
mcframe.loc[3, 'Category'] = np.NaN
mcframe.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,NaN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [18]:
avg_total_fat = mcframe['TotalFat'].mean()
mcframe['TotalFat'].fillna(value=avg_total_fat).head()

0    13.000000
1    14.189189
2    23.000000
3    28.000000
4    23.000000
Name: TotalFat, dtype: float64

### Forward Fill - ffil<br>
To refill NaN or NULL use value from previous row.

In [20]:
mcframe['Saturated Fat'].fillna(method='ffill').head()
# 1 & 2 have been updated to value from 0 row

0     5.0
1     5.0
2     5.0
3    10.0
4     8.0
Name: Saturated Fat, dtype: float64

## Sorting the Data Frame

In [29]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Serving Size']
)
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

### sort_values()
* by= set of columns
* axis= rows or cols
* ascending = True/False
* inplace=False/True
* kind='quicksort' - which algorithm to sort
* na_position='last' - where should be NaN/NULL, at last or at first

In [30]:
mcframe.sort_values(by='Calories').head()

         Category                    Item  Serving Size  Calories  TotalFat
125     Beverages  Diet Dr Pepper (Child)  12 fl oz cup         0       0.0
138  Coffee & Tea       Iced Tea (Medium)  21 fl oz cup         0       0.0
137  Coffee & Tea        Iced Tea (Small)  16 fl oz cup         0       0.0
136     Beverages     Dasani Water Bottle    16.9 fl oz         0       0.0
145  Coffee & Tea          Coffee (Small)  12 fl oz cup         0       0.0

In [31]:
mcframe.sort_values('Calories', ascending=False).head()

,Category,Item,Serving Size,Calories,TotalFat
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0
34,Breakfast,Big Breakfast with Hotcakes and Egg Whites (La...,15.4 oz (437 g),1050,50.0
33,Breakfast,Big Breakfast with Hotcakes and Egg Whites (Re...,14.9 oz (423 g),990,46.0

### Converting type of a column

In [32]:
print(mcframe.dtypes)
mcframe['Calories'] = mcframe.Calories.astype(np.float32)
mcframe.dtypes

Category         object
Item             object
Serving Size     object
Calories          int64
TotalFat        float64
dtype: object

Category         object
Item             object
Serving Size     object
Calories        float32
TotalFat        float64
dtype: object

In [33]:
mcframe.loc[82, 'Calories'] = np.NaN
print(mcframe.head())
mcframe.loc[82]

    Category                              Item    Serving Size  Calories  \
0  Breakfast                      Egg McMuffin  4.8 oz (136 g)     300.0
1  Breakfast                 Egg White Delight  4.8 oz (135 g)     250.0
2  Breakfast                  Sausage McMuffin  3.9 oz (111 g)     370.0
3  Breakfast         Sausage McMuffin with Egg  5.7 oz (161 g)     450.0
4  Breakfast  Sausage McMuffin with Egg Whites  5.7 oz (161 g)     400.0

   TotalFat
0      13.0
1       8.0
2      23.0
3      28.0
4      23.0

Category                      Chicken & Fish
Item            Chicken McNuggets (40 piece)
Serving Size                 22.8 oz (646 g)
Calories                                 NaN
TotalFat                               118.0
Name: 82, dtype: object

### NaN last and first

In [34]:
mcframe.sort_values('Calories').tail()

,Category,Item,Serving Size,Calories,TotalFat
33,Breakfast,Big Breakfast with Hotcakes and Egg Whites (Re...,14.9 oz (423 g),990.0,46.0
34,Breakfast,Big Breakfast with Hotcakes and Egg Whites (La...,15.4 oz (437 g),1050.0,50.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090.0,56.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150.0,60.0
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),NaN,118.0

In [36]:
mcframe.sort_values('Calories', na_position='first').head()

,Category,Item,Serving Size,Calories,TotalFat
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),NaN,118.0
114,Beverages,Diet Coke (Small),16 fl oz cup,0.0,0.0
139,Coffee & Tea,Iced Tea (Large),30 fl oz cup,0.0,0.0
138,Coffee & Tea,Iced Tea (Medium),21 fl oz cup,0.0,0.0
137,Coffee & Tea,Iced Tea (Small),16 fl oz cup,0.0,0.0

### Sorting by few columns

In [39]:
mcframe.sort_values(by=['Category', 'Item']).head(20)

,Category,Item,Serving Size,Calories,TotalFat
51,Beef & Pork,Bacon Clubhouse Burger,9.5 oz (270 g),720.0,40.0
53,Beef & Pork,Bacon McDouble,5.7 oz (161 g),440.0,22.0
42,Beef & Pork,Big Mac,7.4 oz (211 g),530.0,27.0
49,Beef & Pork,Cheeseburger,4 oz (113 g),290.0,11.0
54,Beef & Pork,Daily Double,6.7 oz (190 g),430.0,22.0
50,Beef & Pork,Double Cheeseburger,5.7 oz (161 g),430.0,21.0
47,Beef & Pork,Double Quarter Pounder with Cheese,10 oz (283 g),750.0,43.0
48,Beef & Pork,Hamburger,3.5 oz (98 g),240.0,8.0
55,Beef & Pork,Jalapeño Double,5.6 oz (159 g),430.0,23.0
52,Beef & Pork,McDouble,5.2 oz (147 g),380.0,17.0
56,Beef & Pork,McRib,7.3 oz (208 g),500.0,26.0
46,Beef & Pork,Quarter Pounder Deluxe,8.6 oz (244 g),540.0,27.0
44,Beef & Pork,Quarter Pounder with Bacon & Cheese,8 oz (227 g),600.0,29.0
45,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,8.3 oz (235 g),610.0,31.0
43,Beef & Pork,Quarter Pounder with Cheese,7.1 oz (202 g),520.0,26.0
130,Beverages,1% Low Fat Milk Jug,1 carton (236 ml),100.0,2.5
113,Beverages,Coca-Cola Classic (Child),12 fl oz cup,100.0,0.0
112,Beverages,Coca-Cola Classic (Large),30 fl oz cup,280.0,0.0
111,Beverages,Coca-Cola Classic (Medium),21 fl oz cup,200.0,0.0
110,Beverages,Coca-Cola Classic (Small),16 fl oz cup,140.0,0.0

#### Sorting 1st col asc and 2nd col desc

In [41]:
mcframe.sort_values(['Category', 'Item'], ascending=[False, True]).head(20)

,Category,Item,Serving Size,Calories,TotalFat
101,Snacks & Sides,Apple Slices,1.2 oz (34 g),15.0,0.0
90,Snacks & Sides,Chipotle BBQ Snack Wrap (Crispy Chicken),4.6 oz (130 g),340.0,15.0
91,Snacks & Sides,Chipotle BBQ Snack Wrap (Grilled Chicken),4.3 oz (123 g),260.0,8.0
102,Snacks & Sides,Fruit 'n Yogurt Parfait,5.2 oz (149 g),150.0,2.0
92,Snacks & Sides,Honey Mustard Snack Wrap (Crispy Chicken),4.3 oz (123 g),330.0,15.0
93,Snacks & Sides,Honey Mustard Snack Wrap (Grilled Chicken),4.1 oz (116 g),250.0,8.0
99,Snacks & Sides,Kids French Fries,1.3 oz (38 g),110.0,5.0
98,Snacks & Sides,Large French Fries,5.9 oz (168 g),510.0,24.0
97,Snacks & Sides,Medium French Fries,3.9 oz (111 g),340.0,16.0
94,Snacks & Sides,Ranch Snack Wrap (Crispy Chicken),4.5 oz (128 g),360.0,20.0
95,Snacks & Sides,Ranch Snack Wrap (Grilled Chicken),4.3 oz (121 g),280.0,13.0
100,Snacks & Sides,Side Salad,3.1 oz (87 g),20.0,0.0
96,Snacks & Sides,Small French Fries,2.6 oz (75 g),230.0,11.0
234,Smoothies & Shakes,Blueberry Pomegranate Smoothie (Large),22 fl oz cup,340.0,1.0
233,Smoothies & Shakes,Blueberry Pomegranate Smoothie (Medium),16 fl oz cup,260.0,1.0
232,Smoothies & Shakes,Blueberry Pomegranate Smoothie (Small),12 fl oz cup,220.0,0.5
249,Smoothies & Shakes,Chocolate Shake (Large),22 fl oz cup,850.0,23.0
248,Smoothies & Shakes,Chocolate Shake (Medium),16 fl oz cup,700.0,20.0
247,Smoothies & Shakes,Chocolate Shake (Small),12 fl oz cup,560.0,16.0
240,Smoothies & Shakes,Mango Pineapple Smoothie (Large),22 fl oz cup,340.0,1.0

### Sorting by index

In [42]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Serving Size'],
    index_col='Item'
)
mcframe.head()

,Category,Serving Size,Calories,TotalFat
Item,,,,
Egg McMuffin,Breakfast,4.8 oz (136 g),300,13.0
Egg White Delight,Breakfast,4.8 oz (135 g),250,8.0
Sausage McMuffin,Breakfast,3.9 oz (111 g),370,23.0
Sausage McMuffin with Egg,Breakfast,5.7 oz (161 g),450,28.0
Sausage McMuffin with Egg Whites,Breakfast,5.7 oz (161 g),400,23.0

In [44]:
mcframe.sort_index().head()

,Category,Serving Size,Calories,TotalFat
Item,,,,
1% Low Fat Milk Jug,Beverages,1 carton (236 ml),100,2.5
Apple Slices,Snacks & Sides,1.2 oz (34 g),15,0.0
Bacon Buffalo Ranch McChicken,Chicken & Fish,5.7 oz (161 g),430,21.0
Bacon Cheddar McChicken,Chicken & Fish,6 oz (171 g),480,24.0
Bacon Clubhouse Burger,Beef & Pork,9.5 oz (270 g),720,40.0

### Sorting with case insensitive

In [45]:
fuel = pd.read_csv('./course-files/course-sources/fuel.csv',
                  usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type','Combined MPG (FT1)'],
                  index_col='Vehicle ID',
                  low_memory=False)
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0

In [46]:
fuel.sort_values(['Make','Model']).head(20)  # Acura < ASC ...

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0
28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0
27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Regular,13.0
28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Regular,13.0
1032,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Regular,16.0
1033,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Regular,13.0
3347,1987,ASC Incorporated,GNX,Midsize Cars,Premium,16.0
13309,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Regular,22.0
13311,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Regular,20.0
13310,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Regular,24.0
14038,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,22.0
14040,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,20.0
14039,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,24.0
14834,1999,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,22.0
14836,1999,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,20.0
14835,1999,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,24.0
11789,1995,Acura,2.5TL,Compact Cars,Premium,20.0
12673,1996,Acura,2.5TL/3.2TL,Compact Cars,Premium,20.0
12674,1996,Acura,2.5TL/3.2TL,Compact Cars,Premium,19.0
13421,1997,Acura,2.5TL/3.2TL,Compact Cars,Premium,20.0

In [49]:
# it works, but function is ran in every columns from arg by=...
fuel.sort_values(
    by=['Make', 'Model'],
    key=lambda txt: txt.str.lower()
).head(20)

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
13309,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Regular,22.0
13311,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Regular,20.0
13310,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Regular,24.0
14038,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,22.0
14040,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,20.0
14039,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,24.0
14834,1999,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,22.0
14836,1999,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,20.0
14835,1999,Acura,2.3CL/3.0CL,Subcompact Cars,Regular,24.0
11789,1995,Acura,2.5TL,Compact Cars,Premium,20.0
12673,1996,Acura,2.5TL/3.2TL,Compact Cars,Premium,20.0
12674,1996,Acura,2.5TL/3.2TL,Compact Cars,Premium,19.0
13421,1997,Acura,2.5TL/3.2TL,Compact Cars,Premium,20.0
13422,1997,Acura,2.5TL/3.2TL,Compact Cars,Premium,19.0
14163,1998,Acura,2.5TL/3.2TL,Compact Cars,Premium,20.0
14164,1998,Acura,2.5TL/3.2TL,Compact Cars,Premium,19.0
16573,2001,Acura,3.2CL,Compact Cars,Premium,20.0
17489,2002,Acura,3.2CL,Compact Cars,Premium,21.0
18459,2003,Acura,3.2CL,Compact Cars,Premium,21.0
18458,2003,Acura,3.2CL,Compact Cars,Premium,20.0

## Types

In [59]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Serving Size'],
#     index_col='Item'
)
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [52]:
mcframe.dtypes

Category         object
Item             object
Serving Size     object
Calories          int64
TotalFat        float64
dtype: object

In [53]:
mcframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  260 non-null    object
 3   Calories      260 non-null    int64
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 10.3+ KB

### INT not accept NaN !!!

In [55]:
mcframe.info(memory_usage='deep')  # better precision

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  260 non-null    object
 3   Calories      260 non-null    int64
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 61.7 KB

In [62]:
mcframe.loc[1, 'Serving Size'] = np.NaN
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,13.0
1,Breakfast,Egg White Delight,NaN,250.0,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),NaN,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0

### Update changes the column type

In [60]:
print(mcframe.Calories.dtype)
mcframe.loc[2, 'Calories'] = np.NaN  # try to change int to NaN
print(mcframe.Calories.dtype)

int64
float64

In [63]:
mcframe.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      259 non-null    float64
 4   TotalFat      260 non-null    float64
dtypes: float64(2), object(3)
memory usage: 61.6 KB

In [66]:
# mcframe['Calories'].astype(np.int64)  # ValueError
mcframe['Calories'].fillna(value=0, inplace=True)
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,13.0
1,Breakfast,Egg White Delight,NaN,250.0,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0.0,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0

In [70]:
mcframe['Calories'] = mcframe['Calories'].astype('int')  # which int?
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,NaN,250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),0,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [71]:
# the type has changed int64 -> float64 -> int32 because data can be contained in int32.
# astype('int') automatically check if data can be contained in smaller type
mcframe.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    object
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      260 non-null    int32
 4   TotalFat      260 non-null    float64
dtypes: float64(1), int32(1), object(3)
memory usage: 60.6 KB

### Repeated values

In [72]:
mcframe['Category'].value_counts()

Coffee & Tea          95
Breakfast             42
Smoothies & Shakes    28
Beverages             27
Chicken & Fish        27
Beef & Pork           15
Snacks & Sides        13
Desserts               7
Salads                 6
Name: Category, dtype: int64

In [73]:
mcframe['Category'] = mcframe['Category'].astype('category')
mcframe.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    category
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    object
 3   Calories      260 non-null    int32
 4   TotalFat      260 non-null    float64
dtypes: category(1), float64(1), int32(1), object(2)
memory usage: 44.3 KB

In [74]:
mcframe['Serving Size'].value_counts()

16 fl oz cup       45
12 fl oz cup       38
22 fl oz cup       20
20 fl oz cup       16
30 fl oz cup        7
                   ..
1.2 oz (34 g)       1
2.7 oz (77 g)       1
10.1 oz (285 g)     1
4.8 oz (136 g)      1
15.4 oz (437 g)     1
Name: Serving Size, Length: 106, dtype: int64

In [75]:
mcframe['Serving Size'] = mcframe['Serving Size'].astype('category')
mcframe.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      260 non-null    category
 1   Item          260 non-null    object
 2   Serving Size  259 non-null    category
 3   Calories      260 non-null    int32
 4   TotalFat      260 non-null    float64
dtypes: category(2), float64(1), int32(1), object(1)
memory usage: 38.2 KB

## Ranking

In [76]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Serving Size'],
#     index_col='Item'
)
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [77]:
mcframe.Calories.rank().head()

0    115.0
1     82.5
2    146.0
3    178.5
4    156.0
Name: Calories, dtype: float64

In [78]:
mcframe['CaloriesRank'] = mcframe.Calories.rank()
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0,115.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0,82.5
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0,146.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0,178.5
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0,156.0

In [79]:
mcframe.sort_values('Calories').head(20)
# 0 cals are 16 times. 1st place + 16th place = 17th => 17th / 2 = 8.5

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
125,Beverages,Diet Dr Pepper (Child),12 fl oz cup,0,0.0,8.5
138,Coffee & Tea,Iced Tea (Medium),21 fl oz cup,0,0.0,8.5
137,Coffee & Tea,Iced Tea (Small),16 fl oz cup,0,0.0,8.5
136,Beverages,Dasani Water Bottle,16.9 fl oz,0,0.0,8.5
145,Coffee & Tea,Coffee (Small),12 fl oz cup,0,0.0,8.5
147,Coffee & Tea,Coffee (Large),16 fl oz cup,0,0.0,8.5
124,Beverages,Diet Dr Pepper (Large),30 fl oz cup,0,0.0,8.5
139,Coffee & Tea,Iced Tea (Large),30 fl oz cup,0,0.0,8.5
122,Beverages,Diet Dr Pepper (Small),16 fl oz cup,0,0.0,8.5
123,Beverages,Diet Dr Pepper (Medium),21 fl oz cup,0,0.0,8.5
117,Beverages,Diet Coke (Child),12 fl oz cup,0,0.0,8.5
116,Beverages,Diet Coke (Large),30 fl oz cup,0,0.0,8.5
115,Beverages,Diet Coke (Medium),21 fl oz cup,0,0.0,8.5
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0.0,8.5
146,Coffee & Tea,Coffee (Medium),16 fl oz cup,0,0.0,8.5
140,Coffee & Tea,Iced Tea (Child),12 fl oz cup,0,0.0,8.5
101,Snacks & Sides,Apple Slices,1.2 oz (34 g),15,0.0,17.0
100,Snacks & Sides,Side Salad,3.1 oz (87 g),20,0.0,18.0
106,Desserts,Kids Ice Cream Cone,1 oz (29 g),45,1.5,19.0
132,Beverages,Minute Maid 100% Apple Juice Box,6 fl oz (177 ml),80,0.0,20.5

### rank arguments
* `axis=0`
* `method='average'` - default method to determine place in ranking for the same values
* `numeric_only=None`
* `na_option='keep'`
* `ascending=True`

In [81]:
mcframe['CaloriesRankDesc'] = mcframe.Calories.rank(ascending=False)
mcframe.sort_values('Calories', ascending=False).head(20)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank,CaloriesRankDesc
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,260.0,1.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,259.0,2.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,258.0,3.0
34,Breakfast,Big Breakfast with Hotcakes and Egg Whites (La...,15.4 oz (437 g),1050,50.0,257.0,4.0
33,Breakfast,Big Breakfast with Hotcakes and Egg Whites (Re...,14.9 oz (423 g),990,46.0,256.0,5.0
81,Chicken & Fish,Chicken McNuggets (20 piece),11.4 oz (323 g),940,59.0,255.0,6.0
253,Smoothies & Shakes,McFlurry with M&M’s Candies (Medium),16.2 oz (460 g),930,33.0,254.0,7.0
249,Smoothies & Shakes,Chocolate Shake (Large),22 fl oz cup,850,23.0,252.5,8.5
246,Smoothies & Shakes,Strawberry Shake (Large),22 fl oz cup,850,24.0,252.5,8.5
251,Smoothies & Shakes,Shamrock Shake (Large),22 fl oz cup,820,23.0,250.5,10.5
243,Smoothies & Shakes,Vanilla Shake (Large),22 fl oz cup,820,23.0,250.5,10.5
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810,32.0,249.0,12.0
28,Breakfast,Big Breakfast (Large Biscuit),10 oz (283 g),800,52.0,248.0,13.0
231,Coffee & Tea,Frappé Chocolate Chip (Large),22 fl oz cup,760,31.0,247.0,14.0
47,Beef & Pork,Double Quarter Pounder with Cheese,10 oz (283 g),750,43.0,245.5,15.5
63,Chicken & Fish,Bacon Clubhouse Crispy Chicken Sandwich,10 oz (284 g),750,38.0,245.5,15.5
27,Breakfast,Big Breakfast (Regular Biscuit),9.5 oz (269 g),740,48.0,244.0,17.0
51,Beef & Pork,Bacon Clubhouse Burger,9.5 oz (270 g),720,40.0,243.0,18.0
248,Smoothies & Shakes,Chocolate Shake (Medium),16 fl oz cup,700,20.0,242.0,19.0
30,Breakfast,Big Breakfast with Egg Whites (Large Biscuit),10.1 oz (286 g),690,41.0,240.0,21.0

### The largest, the smallest values in columns

In [82]:
mcframe.sort_values(by='Calories', ascending=False).head(3)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank,CaloriesRankDesc
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,260.0,1.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,259.0,2.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,258.0,3.0

In [83]:
mcframe.nlargest(n=3, columns='Calories')  # how many and what

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank,CaloriesRankDesc
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,260.0,1.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,259.0,2.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,258.0,3.0

In [89]:
mcframe.sort_values('Calories', ascending=False).tail(3)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank,CaloriesRankDesc
115,Beverages,Diet Coke (Medium),21 fl oz cup,0,0.0,8.5,252.5
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0.0,8.5,252.5
146,Coffee & Tea,Coffee (Medium),16 fl oz cup,0,0.0,8.5,252.5

In [88]:
mcframe.nsmallest(n=3, columns='Calories')

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank,CaloriesRankDesc
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0.0,8.5,252.5
115,Beverages,Diet Coke (Medium),21 fl oz cup,0,0.0,8.5,252.5
116,Beverages,Diet Coke (Large),30 fl oz cup,0,0.0,8.5,252.5

## Filtering data in Data Frame

In [90]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Serving Size'],
#     index_col='Item'
)
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [91]:
mcframe.Calories >= 400

0      False
1      False
2      False
3       True
4       True
       ...
255     True
256     True
257    False
258     True
259     True
Name: Calories, Length: 260, dtype: bool

In [92]:
(mcframe.Calories >= 400).head()

0    False
1    False
2    False
3     True
4     True
Name: Calories, dtype: bool

In [93]:
calories_grater_equal_400 = mcframe.Calories >= 400
mcframe[calories_grater_equal_400].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [94]:
totalFat_less_equal_20 = mcframe['TotalFat'] <= 20
mcframe[totalFat_less_equal_20].head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
8,Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (R...",5.4 oz (153 g),410,20.0
16,Breakfast,Southern Style Chicken Biscuit (Regular Biscuit),5 oz (143 g),410,20.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0

In [95]:
mcframe[mcframe['Calories'] >= 400].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [96]:
mcframe[mcframe['TotalFat'] <= 20].head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
8,Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (R...",5.4 oz (153 g),410,20.0
16,Breakfast,Southern Style Chicken Biscuit (Regular Biscuit),5 oz (143 g),410,20.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0

In [97]:
is_breakfast = mcframe['Category'] == 'Breakfast'
mcframe[is_breakfast & calories_grater_equal_400].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [98]:
mcframe[is_breakfast
        & calories_grater_equal_400
        & totalFat_less_equal_20].head()

,Category,Item,Serving Size,Calories,TotalFat
8,Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (R...",5.4 oz (153 g),410,20.0
16,Breakfast,Southern Style Chicken Biscuit (Regular Biscuit),5 oz (143 g),410,20.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0
39,Breakfast,Cinnamon Melts,4 oz (114 g),460,19.0

### Negation

In [100]:
mcframe[~ is_breakfast].head()

,Category,Item,Serving Size,Calories,TotalFat
42,Beef & Pork,Big Mac,7.4 oz (211 g),530,27.0
43,Beef & Pork,Quarter Pounder with Cheese,7.1 oz (202 g),520,26.0
44,Beef & Pork,Quarter Pounder with Bacon & Cheese,8 oz (227 g),600,29.0
45,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,8.3 oz (235 g),610,31.0
46,Beef & Pork,Quarter Pounder Deluxe,8.6 oz (244 g),540,27.0

In [21]:
color = ['green', 'green', 'blue', 'blue', 'red', 'red', 'white']
size = ['S', 'S', 'S', 'M', 'M', 'M', 'L']
gender = ['M', 'W', 'M', 'W', 'M', 'W', 'U']
clothes = pd.DataFrame(dict(color=color, size=size, gender=gender))
clothes

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white    L      U

In [22]:
is_color_blue = clothes.color == 'blue'
is_color_green = clothes.color == 'green'
is_color_red = clothes.color == 'red'
is_gender_m = clothes.gender == 'M'
is_gender_w = clothes.gender == 'W'
is_size_s = clothes['size'] == 'S'
is_size_m = clothes['size'] == 'M'
print(clothes.size)
is_size_s

21

0     True
1     True
2     True
3    False
4    False
5    False
6    False
Name: size, dtype: bool

In [103]:
# I want blue cloth for men in M size:
clothes[is_color_blue & is_gender_m & is_size_s]

  color size gender
2  blue    S      M

In [104]:
# I want blue cloth or for men or size S
clothes[is_color_blue | is_gender_m | is_size_s]

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M

In [106]:
clothes[is_color_blue & is_gender_m | is_size_m]

  color size gender
2  blue    S      M
3  blue    M      W
4   red    M      M
5   red    M      W

In [107]:
clothes[is_size_m | is_color_blue & is_gender_m]

  color size gender
2  blue    S      M
3  blue    M      W
4   red    M      M
5   red    M      W

In [108]:
# &=and is stronger
all(
    clothes[is_color_blue & is_gender_m | is_size_m] ==
    clothes[is_size_m | is_color_blue & is_gender_m]
)

True

In [109]:
clothes[(is_size_m | is_color_blue) & is_gender_m]

  color size gender
2  blue    S      M
4   red    M      M

## Where and Query

In [2]:
mcframe = pd.read_csv(
    './course-files/course-sources/Mcdonalds.csv',
    usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Serving Size'],
#     index_col='Item'
)
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [4]:
has_400_cal_or_more = mcframe['Calories'] >= 400
has_400_cal_or_more[:5]

0    False
1    False
2    False
3     True
4     True
Name: Calories, dtype: bool

In [5]:
mcframe.where(has_400_cal_or_more).head()

,Category,Item,Serving Size,Calories,TotalFat
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0

In [6]:
mcframe.where(~ has_400_cal_or_more).head()

    Category               Item    Serving Size  Calories  TotalFat
0  Breakfast       Egg McMuffin  4.8 oz (136 g)     300.0      13.0
1  Breakfast  Egg White Delight  4.8 oz (135 g)     250.0       8.0
2  Breakfast   Sausage McMuffin  3.9 oz (111 g)     370.0      23.0
3        NaN                NaN             NaN       NaN       NaN
4        NaN                NaN             NaN       NaN       NaN

In [8]:
mcframe[has_400_cal_or_more].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [10]:
mcframe[~ has_400_cal_or_more].head()

     Category               Item    Serving Size  Calories  TotalFat
0   Breakfast       Egg McMuffin  4.8 oz (136 g)       300      13.0
1   Breakfast  Egg White Delight  4.8 oz (135 g)       250       8.0
2   Breakfast   Sausage McMuffin  3.9 oz (111 g)       370      23.0
35  Breakfast           Hotcakes  5.3 oz (151 g)       350       9.0
37  Breakfast    Sausage Burrito  3.9 oz (111 g)       300      16.0

In [11]:
mcframe.where(has_400_cal_or_more).dropna().head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520.0,30.0

In [14]:
# any/all: if all vals in row are NaN then drop
mcframe.where(has_400_cal_or_more).dropna(how='all').head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520.0,30.0

In [15]:
mcframe.query('Category == "Desserts"').head()

     Category                   Item     Serving Size  Calories  TotalFat
103  Desserts        Baked Apple Pie    2.7 oz (77 g)       250      13.0
104  Desserts  Chocolate Chip Cookie  1 cookie (33 g)       160       8.0
105  Desserts  Oatmeal Raisin Cookie  1 cookie (33 g)       150       6.0
106  Desserts    Kids Ice Cream Cone      1 oz (29 g)        45       1.5
107  Desserts       Hot Fudge Sundae   6.3 oz (179 g)       330       9.0

In [17]:
mcframe.query('Category in ["Desserts", "Beverages"]').tail()

,Category,Item,Serving Size,Calories,TotalFat
132,Beverages,Minute Maid 100% Apple Juice Box,6 fl oz (177 ml),80,0.0
133,Beverages,Minute Maid Orange Juice (Small),12 fl oz cup,150,0.0
134,Beverages,Minute Maid Orange Juice (Medium),16 fl oz cup,190,0.0
135,Beverages,Minute Maid Orange Juice (Large),22 fl oz cup,280,0.0
136,Beverages,Dasani Water Bottle,16.9 fl oz,0,0.0

In [18]:
mcframe.query('Category == "Desserts" and Calories < 200').head()

     Category                   Item     Serving Size  Calories  TotalFat
104  Desserts  Chocolate Chip Cookie  1 cookie (33 g)       160       8.0
105  Desserts  Oatmeal Raisin Cookie  1 cookie (33 g)       150       6.0
106  Desserts    Kids Ice Cream Cone      1 oz (29 g)        45       1.5

In [51]:
mcframe.query('Category == "Desserts"' and 'Calories < 200').head()  # doesn't work properly

,Category,Item,Serving Size,Calories,TotalFat
38,Breakfast,Hash Brown,2 oz (56 g),150,9.0
78,Chicken & Fish,Chicken McNuggets (4 piece),2.3 oz (65 g),190,12.0
84,Salads,Premium Bacon Ranch Salad (without Chicken),7.9 oz (223 g),140,7.0
87,Salads,Premium Southwest Salad (without Chicken),8.1 oz (230 g),140,4.5
99,Snacks & Sides,Kids French Fries,1.3 oz (38 g),110,5.0

## Specialised filtering: isin, isnull, notnull, between

In [23]:
clothes

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white    L      U

In [24]:
clothes[is_color_blue | is_color_green | is_color_red]

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W

In [26]:
my_colors = clothes['color'].isin(['blue', 'green', 'red'])
my_colors

0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: color, dtype: bool

In [27]:
clothes[my_colors]

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W

In [31]:
clothes.loc[6, 'size']

'L'

In [33]:
clothes.loc[6, 'size'] = np.NaN
clothes.loc[6]

color     white
size        NaN
gender        U
Name: 6, dtype: object

In [36]:
has_size = clothes['size'].notnull()  # notnull / notna  are the same
has_size

0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: size, dtype: bool

In [39]:
clothes[has_size]

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W

In [40]:
size_unknown = clothes['size'].isnull()  # isnull / isna  are the same
size_unknown

0    False
1    False
2    False
3    False
4    False
5    False
6     True
Name: size, dtype: bool

In [41]:
clothes[size_unknown]

   color size gender
6  white  NaN      U

In [42]:
mcframe.head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [43]:
cals_grater_equal_300 = mcframe['Calories'] >= 300
cals_lower_equal_400 = mcframe['Calories'] <= 400
mcframe[cals_grater_equal_300 & cals_lower_equal_400].head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0
35,Breakfast,Hotcakes,5.3 oz (151 g),350,9.0

In [44]:
cals_between_300_400 = mcframe['Calories'].between(300,400)  # with 300 and 400
cals_between_300_400.head()

0     True
1    False
2     True
3    False
4     True
Name: Calories, dtype: bool

In [46]:
mcframe[cals_between_300_400].head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0
35,Breakfast,Hotcakes,5.3 oz (151 g),350,9.0

## Duplicates in Data Frame

In [67]:
color = ['green', 'green', 'blue', 'blue', 'red', 'red', 'white']
size = ['S', 'S', 'S', 'M', 'M', 'M', 'L']
gender = ['M', 'W', 'M', 'W', 'M', 'W', 'U']
clothes = pd.DataFrame(dict(color=color, size=size, gender=gender))
clothes

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white    L      U

### is_unique, unique(), nunique()

In [58]:
clothes['color'].is_unique

False

In [60]:
clothes['color'].unique()  # distinct or grouping

array(['green', 'blue', 'red', 'white'], dtype=object)

In [62]:
clothes['color'].nunique()  # how many unique vals

4

In [64]:
clothes['color'].unique().size == clothes['color'].nunique()

True

In [68]:
clothes.loc[6, 'color'] = np.NaN
clothes

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6    NaN    L      U

In [69]:
clothes['color'].unique()

array(['green', 'blue', 'red', nan], dtype=object)

In [70]:
clothes['color'].nunique()  # nunique doesn't count NaN

3

In [71]:
clothes['color'].unique().size == clothes['color'].nunique()

False

### duplicated()
* `keep='first'/'last'/False` :
    * first: first is not duplicate, next is duplicate
    * last: last is not a duplicate
    * False: only not duplicated values

In [75]:
clothes['color'].duplicated(keep='first')

0    False
1     True
2    False
3     True
4    False
5     True
6    False
Name: color, dtype: bool

In [76]:
clothes['color'].duplicated(keep='last')

0     True
1    False
2     True
3    False
4     True
5    False
6    False
Name: color, dtype: bool

In [77]:
clothes['color'].duplicated(keep=False)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: color, dtype: bool

In [79]:
unique_values = clothes['color'].duplicated(keep='first')
clothes[~unique_values]  # not

   color size gender
0  green    S      M
2   blue    S      M
4    red    M      M
6    NaN    L      U

### drop_duplicates()

In [80]:
clothes.drop_duplicates(subset=['color'], keep='first')

   color size gender
0  green    S      M
2   blue    S      M
4    red    M      M
6    NaN    L      U

In [81]:
clothes.drop_duplicates(['color', 'size'])

   color size gender
0  green    S      M
2   blue    S      M
3   blue    M      W
4    red    M      M
6    NaN    L      U

In [86]:
duplicated_size_color = clothes[['color', 'size']].duplicated()
duplicated_size_color

0    False
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [87]:
clothes[duplicated_size_color]

   color size gender
1  green    S      W
5    red    M      W

In [88]:
clothes.query("color == 'green' & size == 'S' | color == 'red' & size == 'M'")

   color size gender
0  green    S      M
1  green    S      W
4    red    M      M
5    red    M      W

In [96]:
duplicate1 = clothes[duplicated_size_color].iloc[0]
duplicate2 = clothes[duplicated_size_color].iloc[1]
duplicate1, duplicate2

(color     green
 size          S
 gender        W
 Name: 1, dtype: object,
 color     red
 size        M
 gender      W
 Name: 5, dtype: object)

In [97]:
duplicate1['color']

'green'

In [115]:
clothes.query(f"color == '{duplicate1['color']}' & size == '{duplicate1['size']}' | color == '{duplicate2['color']}' & size == '{duplicate2['size']}'")

   color size gender
0  green    S      M
1  green    S      W
4    red    M      M
5    red    M      W

In [121]:
clothes[
    (clothes['color'] == duplicate1['color']) & (clothes['size'] == duplicate1['size'])
    | (clothes['color'] == duplicate2['color']) & (clothes['size'] == duplicate2['size'])
]

   color size gender
0  green    S      M
1  green    S      W
4    red    M      M
5    red    M      W