# DataGrouping

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

%matplotlib inline

## Introduction to grouping

In [2]:
products = pd.read_csv('./course-files/course-sources/WA_Sales_Products_2012-14.csv')
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [3]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88475 entries, 0 to 88474
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Retailer country   88475 non-null  object
 1   Order method type  88475 non-null  object
 2   Retailer type      88475 non-null  object
 3   Product line       88475 non-null  object
 4   Product type       88475 non-null  object
 5   Product            88475 non-null  object
 6   Year               88475 non-null  int64
 7   Quarter            88475 non-null  object
 8   Revenue            88475 non-null  float64
 9   Quantity           88475 non-null  int64
 10  Gross margin       87894 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 7.4+ MB

In [4]:
products.describe()

               Year       Revenue      Quantity  Gross margin
count  88475.000000  8.847500e+04  88475.000000  87894.000000
mean    2012.855281  4.263829e+04    780.586166      0.449718
std        0.778342  6.578402e+04   1541.645422      0.123642
min     2012.000000  0.000000e+00      1.000000    -12.853678
25%     2012.000000  8.184360e+03    131.000000      0.369880
50%     2013.000000  2.102628e+04    333.000000      0.450634
75%     2013.000000  5.039060e+04    816.000000      0.520130
max     2014.000000  1.635688e+06  67875.000000      0.770476

In [5]:
products['Retailer country'].value_counts()

United States     7482
Canada            5923
France            5779
Germany           5397
Japan             5359
United Kingdom    5102
Netherlands       4199
Switzerland       4103
Italy             4018
Austria           3862
Mexico            3845
Belgium           3710
Australia         3665
China             3652
Spain             3557
Singapore         3443
Finland           3409
Korea             3399
Brazil            3288
Sweden            2925
Denmark           2358
Name: Retailer country, dtype: int64

In [6]:
products['Retailer country'].nunique()

21

In [7]:
countries = products['Retailer country'].unique()
countries

array(['United States', 'Canada', 'Mexico', 'Brazil', 'Japan',
       'Singapore', 'Korea', 'China', 'Australia', 'Netherlands',
       'Sweden', 'Denmark', 'Finland', 'France', 'Germany', 'Switzerland',
       'United Kingdom', 'Belgium', 'Austria', 'Italy', 'Spain'],
      dtype=object)

In [8]:
my_own_groups = dict()
for country in countries:
    my_own_groups[country] = products[products['Retailer country'] == country]

my_own_groups

{'United States':       Retailer country Order method type  Retailer type          Product line  \
 0        United States               Fax  Outdoors Shop     Camping Equipment
 1        United States               Fax  Outdoors Shop     Camping Equipment
 2        United States               Fax  Outdoors Shop     Camping Equipment
 3        United States               Fax  Outdoors Shop     Camping Equipment
 4        United States               Fax  Outdoors Shop     Camping Equipment
 ...                ...               ...            ...                   ...
 84049    United States       Sales visit  Eyewear Store  Personal Accessories
 84050    United States       Sales visit  Eyewear Store  Personal Accessories
 84051    United States       Sales visit  Eyewear Store  Personal Accessories
 84052    United States       Sales visit  Eyewear Store  Personal Accessories
 84053    United States       Sales visit  Eyewear Store  Personal Accessories

         Product type                    Product  Year  Quarter    Revenue  \
 0       Cooking Gear  TrailChef Deluxe Cook Set  2012  Q1 2012   59628.66
 1       Cooking Gear     TrailChef Double Flame  2012  Q1 2012   35950.32
 2              Tents                  Star Dome  2012  Q1 2012   89940.48
 3              Tents               Star Gazer 2  2012  Q1 2012  165883.41
 4      Sleeping Bags            Hibernator Lite  2012  Q1 2012  119822.20
 ...              ...                        ...   ...      ...        ...
 84049        Eyewear                  Polar Ice  2014  Q3 2014   20957.00
 84050        Eyewear               Polar Sports  2014  Q3 2014  105495.85
 84051        Eyewear                 Polar Wave  2014  Q3 2014    6540.48
 84052        Eyewear              Polar Extreme  2014  Q3 2014    6340.05
 84053     Binoculars                  Seeker 35  2014  Q3 2014   83324.99

        Quantity  Gross margin
 0           489      0.347548
 1           252      0.474274
 2           147      0.352772
 3           303      0.282938
 4          1415      0.291450
 ...         ...           ...
 84049       218      0.483112
 84050       905      0.494896
 84051        72      0.547336
 84052        45      0.485414
 84053       833      0.288314

 [7482 rows x 11 columns],
 'Canada':       Retailer country Order method type  Retailer type          Product line  \
 864             Canada               Fax  Outdoors Shop  Personal Accessories
 865             Canada               Fax  Outdoors Shop  Personal Accessories
 866             Canada               Fax  Outdoors Shop  Personal Accessories
 867             Canada               Fax  Outdoors Shop  Personal Accessories
 868             Canada               Fax  Outdoors Shop  Personal Accessories
 ...                ...               ...            ...                   ...
 84363           Canada               Web   Sports Store        Golf Equipment
 84364           Canada               Web   Sports Store        Golf Equipment
 84365           Canada               Web   Sports Store        Golf Equipment
 84366           Canada               Web   Sports Store        Golf Equipment
 84367           Canada               Web   Sports Store        Golf Equipment

            Product type                Product  Year  Quarter   Revenue  \
 864             Watches                  Venue  2012  Q1 2012  12045.00
 865             Watches                     TX  2012  Q1 2012  20960.00
 866             Watches                 Legend  2012  Q1 2012   3740.00
 867             Watches                 Kodiak  2012  Q1 2012  33445.20
 868             Eyewear                  Capri  2012  Q1 2012  23784.30
 ...                 ...                    ...   ...      ...       ...
 84363           Putters      Course Pro Putter  2014  Q3 2014  68133.45
 84364           Putters  Blue Steel Max Putter  2014  Q3 2014  37408.80
 84365  Golf Accessories    Course Pro Umbrella  2014  Q3 2014  14356.65
 84366  Golf Accessories    Course Pro Golf Bag  2014  Q3 2014  24167.44
 84367  Golf Accessories      Course Pro Gloves  2014  Q3 2014  13753.76

        Quantity  Gross margin
 864         165      0.418630
 865         114      0.450544
 866          17      0.473455
 867         271      0.455317
 868         621      0.340707
 ...         ...           ...
 84363      1735      0.385281
 84364       218      0.523310
 84365      1155      0.479485
 84366       116      0.617452
 84367      2566      0.524254

 [5923 rows x 11 columns],
 'Mexico':       Retailer country Order method type Retailer type          Product line  \
 1468            Mexico               Web     Golf Shop  Personal Accessories
 1469            Mexico               Web     Golf Shop  Personal Accessories
 1470            Mexico               Web     Golf Shop  Personal Accessories
 1471            Mexico               Web     Golf Shop  Personal Accessories
 1472            Mexico               Web     Golf Shop  Personal Accessories
 ...                ...               ...           ...                   ...
 84551           Mexico               Web  Sports Store        Golf Equipment
 84552           Mexico               Web  Sports Store        Golf Equipment
 84553           Mexico               Web  Sports Store        Golf Equipment
 84554           Mexico               Web  Sports Store        Golf Equipment
 84555           Mexico               Web  Sports Store        Golf Equipment

            Product type                Product  Year  Quarter   Revenue  \
 1468            Watches               Infinity  2012  Q1 2012   4620.00
 1469            Watches                    Lux  2012  Q1 2012   5684.80
 1470            Watches                     TX  2012  Q1 2012   4888.00
 1471            Watches                 Legend  2012  Q1 2012   4593.40
 1472            Eyewear                  Capri  2012  Q1 2012   4825.80
 ...                 ...                    ...   ...      ...       ...
 84551           Putters      Course Pro Putter  2014  Q3 2014  79403.94
 84552           Putters      Blue Steel Putter  2014  Q3 2014  20655.95
 84553           Putters  Blue Steel Max Putter  2014  Q3 2014  45474.00
 84554  Golf Accessories    Course Pro Umbrella  2014  Q3 2014  17861.91
 84555  Golf Accessories      Course Pro Gloves  2014  Q3 2014  14804.32

        Quantity  Gross margin
 1468         21      0.474727
 1469         34      0.478828
 1470         26      0.451702
 1471         17      0.444782
 1472        126      0.340209
 ...         ...           ...
 84551      2022      0.385281
 84552       245      0.511327
 84553       265      0.523310
 84554      1437      0.479485
 84555      2762      0.524254

 [3845 rows x 11 columns],
 'Brazil':       Retailer country Order method type Retailer type          Product line  \
 1833            Brazil               Web     Golf Shop  Personal Accessories
 1834            Brazil               Web     Golf Shop  Personal Accessories
 1835            Brazil               Web     Golf Shop  Personal Accessories
 1836            Brazil               Web     Golf Shop  Personal Accessories
 1837            Brazil               Web     Golf Shop  Personal Accessories
 ...                ...               ...           ...                   ...
 84734           Brazil               Web  Sports Store        Golf Equipment
 84735           Brazil               Web  Sports Store        Golf Equipment
 84736           Brazil               Web  Sports Store        Golf Equipment
 84737           Brazil               Web  Sports Store        Golf Equipment
 84738           Brazil               Web  Sports Store        Golf Equipment

            Product type                Product  Year  Quarter   Revenue  \
 1833            Watches                  Venue  2012  Q1 2012  15987.00
 1834            Watches                    Lux  2012  Q1 2012   7189.60
 1835            Watches                    Sam  2012  Q1 2012   8890.20
 1836            Watches                     TX  2012  Q1 2012  17816.00
 1837            Watches                 Kodiak  2012  Q1 2012   7218.00
 ...                 ...                    ...   ...      ...       ...
 84734           Putters      Blue Steel Putter  2014  Q3 2014  12309.26
 84735           Putters  Blue Steel Max Putter  2014  Q3 2014  23509.20
 84736  Golf Accessories    Course Pro Umbrella  2014  Q3 2014  10391.40
 84737  Golf Accessories    Course Pro Golf Bag  2014  Q3 2014  18750.60
 84738  Golf Accessories      Course Pro Gloves  2014  Q3 2014   8066.80

        Quantity  Gross margin
 1833        219      0.419206
 1834         43      0.478828
 1835        198      0.388419
 1836         93      0.458950
 1837         60      0.444223
 ...         ...           ...
 84734       146      0.511327
 84735       137      0.523310
 84736       828      0.484462
 84737        90      0.617452
 84738      1505      0.524254

 [3288 rows x 11 columns],
 'Japan':       Retailer country Order method type  Retailer type  \
 2146             Japan               Fax  Outdoors Shop
 2147             Japan               Fax  Outdoors Shop
 2148             Japan               Fax  Outdoors Shop
 2149             Japan               Fax  Outdoors Shop
 2150             Japan               Fax  Outdoors Shop
 ...                ...               ...            ...
 85074            Japan       Sales visit   Sports Store
 85075            Japan       Sales visit   Sports Store
 85076            Japan       Sales visit   Sports Store
 85077            Japan       Sales visit   Sports Store
 85078            Japan       Sales visit   Sports Store

                    Product line      Product type                Product  \
 2146          Camping Equipment      Cooking Gear    TrailChef Water Bag
 2147          Camping Equipment      Cooking Gear     TrailChef Utensils
 2148          Camping Equipment          Lanterns        Firefly Extreme
 2149          Camping Equipment          Lanterns        EverGlow Single
 2150   Mountaineering Equipment              Rope          Husky Rope 50
 ...                         ...               ...                    ...
 85074      Personal Accessories        Navigation            Glacier GPS
 85075            Golf Equipment             Irons  Hailstorm Steel Irons
 85076            Golf Equipment           Putters      Course Pro Putter
 85077            Golf Equipment           Putters      Blue Steel Putter
 85078            Golf Equipment  Golf Accessories      Course Pro Gloves

        Year  Quarter   Revenue  Quantity  Gross margin
 2146   2012  Q1 2012  28009.45      7091      0.465823
 2147   2012  Q1 2012  17954.11       957      0.466974
 2148   2012  Q1 2012   7504.70       151      0.434205
 2149   2012  Q1 2012  15638.70       462      0.467061
 2150   2012  Q1 2012  19401.60       129      0.329056
 ...     ...      ...       ...       ...           ...
 85074  2014  Q3 2014  48623.85       517      0.308878
 85075  2014  Q3 2014  68320.20       156      0.495376
 85076  2014  Q3 2014  57373.47      1461      0.385281
 85077  2014  Q3 2014  15681.66       186      0.511327
 85078  2014  Q3 2014  12070.72      2252      0.524254

 [5359 rows x 11 columns],
 'Singapore':       Retailer country Order method type  Retailer type          Product line  \
 2750         Singapore               Fax  Outdoors Shop     Camping Equipment
 2751         Singapore               Fax  Outdoors Shop     Camping Equipment
 2752         Singapore               Fax  Outdoors Shop     Camping Equipment
 2753         Singapore               Fax  Outdoors Shop     Camping Equipment
 2754         Singapore               Fax  Outdoors Shop     Camping Equipment
 ...                ...               ...            ...                   ...
 85255        Singapore               Web  Outdoors Shop  Personal Accessories
 85256        Singapore               Web  Outdoors Shop  Personal Accessories
 85257        Singapore               Web  Outdoors Shop  Personal Accessories
 85258        Singapore               Web  Outdoors Shop  Personal Accessories
 85259        Singapore               Web  Outdoors Shop  Personal Accessories

         Product type                       Product  Year  Quarter   Revenue  \
 2750    Cooking Gear            TrailChef Cook Set  2012  Q1 2012  49777.12
 2751   Sleeping Bags             Hibernator Pillow  2012  Q1 2012   6539.40
 2752           Packs  Canyon Mule Climber Backpack  2012  Q1 2012  30995.25
 2753        Lanterns           Firefly Multi-light  2012  Q1 2012   6502.50
 2754        Lanterns               EverGlow Butane  2012  Q1 2012   6558.01
 ...              ...                           ...   ...      ...       ...
 85255     Binoculars                 Ranger Vision  2014  Q3 2014  56666.50
 85256     Navigation                Glacier Deluxe  2014  Q3 2014  22263.66
 85257     Navigation           Glacier GPS Extreme  2014  Q3 2014  75839.64
 85258     Navigation                   Astro Pilot  2014  Q3 2014  53919.00
 85259     Navigation                     Sky Pilot  2014  Q3 2014  10024.00

        Quantity  Gross margin
 2750        944      0.336810
 2751        378      0.529480
 2752        429      0.273356
 2753        250      0.316417
 2754        103      0.361866
 ...         ...           ...
 85255       337      0.533432
 85256       243      0.443353
 85257       222      0.483432
 85258       294      0.371835
 85259        28      0.358715

 [3443 rows x 11 columns],
 'Korea':       Retailer country Order method type Retailer type        Product line  \
 3074             Korea         Telephone  Sports Store   Camping Equipment
 3075             Korea         Telephone  Sports Store   Camping Equipment
 3076             Korea         Telephone  Sports Store   Camping Equipment
 3077             Korea         Telephone  Sports Store   Camping Equipment
 3078             Korea         Telephone  Sports Store   Camping Equipment
 ...                ...               ...           ...                 ...
 85443            Korea               Web  Sports Store      Golf Equipment
 85444            Korea               Web  Sports Store      Golf Equipment
 85445            Korea               Web  Sports Store      Golf Equipment
 85446            Korea               Web  Sports Store      Golf Equipment
 85447            Korea       Sales visit     Golf Shop  Outdoor Protection

            Product type                    Product  Year  Quarter   Revenue  \
 3074       Cooking Gear          TrailChef Canteen  2012  Q1 2012  12390.90
 3075       Cooking Gear  TrailChef Deluxe Cook Set  2012  Q1 2012  68896.10
 3076       Cooking Gear     TrailChef Single Flame  2012  Q1 2012  52655.64
 3077      Sleeping Bags            Hibernator Lite  2012  Q1 2012  65118.92
 3078           Lanterns                  Firefly 4  2012  Q1 2012   8972.55
 ...                 ...                        ...   ...      ...       ...
 85443           Putters      Blue Steel Max Putter  2014  Q3 2014  48391.20
 85444  Golf Accessories        Course Pro Umbrella  2014  Q3 2014  18433.69
 85445  Golf Accessories        Course Pro Golf Bag  2014  Q3 2014  31459.34
 85446  Golf Accessories          Course Pro Gloves  2014  Q3 2014  17730.88
 85447         Sunscreen                 Sun Shield  2014  Q3 2014   2292.00

        Quantity  Gross margin
 3074       1030      0.449709
 3075        565      0.347548
 3076        839      0.260994
 3077        769      0.291450
 3078        381      0.388535
 ...         ...           ...
 85443       282      0.523310
 85444      1483      0.479485
 85445       151      0.617452
 85446      3308      0.524254
 85447       382      0.540000

 [3399 rows x 11 columns],
 'China':       Retailer country Order method type Retailer type        Product line  \
 3403             China               Fax     Golf Shop      Golf Equipment
 3404             China               Fax     Golf Shop      Golf Equipment
 3405             China               Fax     Golf Shop      Golf Equipment
 3406             China               Fax     Golf Shop      Golf Equipment
 3407             China               Fax     Golf Shop      Golf Equipment
 ...                ...               ...           ...                 ...
 85667            China               Web  Sports Store  Outdoor Protection
 85668            China               Web  Sports Store  Outdoor Protection
 85669            China               Web  Sports Store  Outdoor Protection
 85670            China               Web  Sports Store  Outdoor Protection
 85671            China               Web  Sports Store  Outdoor Protection

             Product type                     Product  Year  Quarter  \
 3403               Irons       Hailstorm Steel Irons  2012  Q1 2012
 3404               Irons  Lady Hailstorm Steel Irons  2012  Q1 2012
 3405               Woods   Hailstorm Steel Woods Set  2012  Q1 2012
 3406             Putters           Blue Steel Putter  2012  Q1 2012
 3407    Golf Accessories         Course Pro Umbrella  2012  Q1 2012
 ...                  ...                         ...   ...      ...
 85667  Insect Repellents            BugShield Lotion  2014  Q3 2014
 85668          Sunscreen                 Sun Blocker  2014  Q3 2014
 85669          Sunscreen              Sun Shelter 15  2014  Q3 2014
 85670          Sunscreen              Sun Shelter 30  2014  Q3 2014
 85671          First Aid             Calamine Relief  2014  Q3 2014

          Revenue  Quantity  Gross margin
 3403    69057.80       214      0.315153
 3404    57590.85       115      0.445356
 3405   198666.24       290      0.501355
 3406    18992.50       214      0.535775
 3407    19082.56      1568      0.506984
 ...          ...       ...           ...
 85667    3381.00       483      0.667143
 85668    1625.00       325      0.610000
 85669    2519.40       510      0.637652
 85670    4944.10      1009      0.622449
 85671     408.00        68      0.528333

 [3652 rows x 11 columns],
 'Australia':       Retailer country Order method type     Retailer type  \
 3735         Australia         Telephone         Golf Shop
 3736         Australia         Telephone         Golf Shop
 3737         Australia         Telephone         Golf Shop
 3738         Australia         Telephone         Golf Shop
 3739         Australia         Telephone         Golf Shop
 ...                ...               ...               ...
 85862        Australia       Sales visit  Department Store
 85863        Australia       Sales visit  Department Store
 85864        Australia       Sales visit  Department Store
 85865        Australia       Sales visit  Department Store
 85866        Australia       Sales visit  Department Store

                Product line Product type                   Product  Year  \
 3735   Personal Accessories      Watches      Mountain Man Digital  2012
 3736   Personal Accessories   Binoculars               Seeker Mini  2012
 3737   Personal Accessories   Navigation               Glacier GPS  2012
 3738         Golf Equipment        Irons     Hailstorm Steel Irons  2012
 3739         Golf Equipment        Irons  Hailstorm Titanium Irons  2012
 ...                     ...          ...                       ...   ...
 85862  Personal Accessories      Watches      Mountain Man Digital  2014
 85863  Personal Accessories      Watches       Mountain Man Deluxe  2014
 85864  Personal Accessories      Watches  Mountain Man Combination  2014
 85865  Personal Accessories   Navigation             Glacier Basic  2014
 85866        Golf Equipment      Putters         Blue Steel Putter  2014

        Quarter   Revenue  Quantity  Gross margin
 3735   Q1 2012   2161.34        53      0.509564
 3736   Q1 2012   5689.60        70      0.507874
 3737   Q1 2012  17337.34       158      0.284152
 3738   Q1 2012  96118.50       255      0.413692

In [11]:
my_own_groups['Belgium'].head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
7270,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
7271,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Deluxe,2012,Q1 2012,5267.96,68,0.496579
7272,Belgium,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,22483.00,96,0.458979
7273,Belgium,Web,Golf Shop,Personal Accessories,Watches,TX,2012,Q1 2012,16100.00,87,0.448898
7274,Belgium,Web,Golf Shop,Personal Accessories,Eyewear,Polar Sun,2012,Q1 2012,2682.52,44,0.571075

In [12]:
my_own_groups['Mexico'].describe()

              Year        Revenue      Quantity  Gross margin
count  3845.000000    3845.000000   3845.000000   3818.000000
mean   2012.847594   36246.971397    662.449155      0.448840
std       0.769929   49260.175492   1149.019516      0.110507
min    2012.000000       0.000000      1.000000     -0.179180
25%    2012.000000    8203.860000    131.000000      0.368511
50%    2013.000000   19364.000000    327.000000      0.449550
75%    2013.000000   43050.240000    749.000000      0.517297
max    2014.000000  464070.900000  19214.000000      0.770476

## The groupby() method
args:
* `by=None`

In [3]:
products = pd.read_csv('./course-files/course-sources/WA_Sales_Products_2012-14.csv')
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [4]:
products.groupby('Retailer country')

In [5]:
groups = products.groupby('Retailer country')
type(groups)

pandas.core.groupby.generic.DataFrameGroupBy

In [7]:
products['Retailer country'].nunique(), len(groups),

(21, 21)

In [29]:
groups.size()  # similar to value_counts()

Retailer country
Australia         3665
Austria           3862
Belgium           3710
Brazil            3288
Canada            5923
China             3652
Denmark           2358
Finland           3409
France            5779
Germany           5397
Italy             4018
Japan             5359
Korea             3399
Mexico            3845
Netherlands       4199
Singapore         3443
Spain             3557
Sweden            2925
Switzerland       4103
United Kingdom    5102
United States     7482
dtype: int64

In [10]:
groups.first()  # get first row from each group

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2161.34,53,0.509564
Austria,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Analog,2012,Q1 2012,6562.30,137,0.373695
Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
Brazil,Web,Golf Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,15987.00,219,0.419206
Canada,Fax,Outdoors Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,12045.00,165,0.418630
China,Fax,Golf Shop,Golf Equipment,Irons,Hailstorm Steel Irons,2012,Q1 2012,69057.80,214,0.315153
Denmark,Web,Golf Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,2482.00,34,0.418630
Finland,Web,Department Store,Camping Equipment,Cooking Gear,TrailChef Water Bag,2012,Q1 2012,16007.34,2586,0.526656
France,Fax,Golf Shop,Golf Equipment,Irons,Lady Hailstorm Steel Irons,2012,Q1 2012,19530.81,39,0.445356
Germany,Mail,Warehouse Store,Camping Equipment,Cooking Gear,TrailChef Cook Set,2012,Q1 2012,21197.46,402,0.336810
Italy,Fax,Outdoors Shop,Mountaineering Equipment,Rope,Husky Rope 50,2012,Q1 2012,18950.40,126,0.329056
Japan,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Water Bag,2012,Q1 2012,28009.45,7091,0.465823
Korea,Telephone,Sports Store,Camping Equipment,Cooking Gear,TrailChef Canteen,2012,Q1 2012,12390.90,1030,0.449709
Mexico,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,4620.00,21,0.474727
Netherlands,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Cup,2012,Q1 2012,4213.85,1187,0.760563
Singapore,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Cook Set,2012,Q1 2012,49777.12,944,0.336810
Spain,Fax,Sports Store,Camping Equipment,Cooking Gear,TrailChef Water Bag,2012,Q1 2012,12191.58,1926,0.537125
Sweden,E-mail,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Kettle,2012,Q1 2012,12371.30,965,0.601404
Switzerland,Fax,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,5500.00,25,0.473455
United Kingdom,Fax,Outdoors Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,41205.00,570,0.419461
United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548

In [12]:
products[products['Retailer country'] == 'Australia'].head(1)

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
3735,Australia,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2161.34,53,0.509564

In [13]:
products[products['Retailer country'] == 'Canada'].head(1)

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
864,Canada,Fax,Outdoors Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,12045.0,165,0.41863

In [16]:
groups.last().head()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,Sales visit,Department Store,Golf Equipment,Putters,Blue Steel Putter,2014,Q3 2014,14248.39,169,0.511327
Austria,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,11759.84,2194,0.524254
Belgium,Web,Sports Store,Personal Accessories,Navigation,Astro Pilot,2014,Q3 2014,33294.00,93,0.350754
Brazil,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,8066.80,1505,0.524254
Canada,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,13753.76,2566,0.524254

In [21]:
groups.groups

{'Australia': [3735, 3736, 3737, 3738, 3739, 3740, 3741, 3742, 3743, 3744, 3745, 3746, 3747, 3748, 3749, 3750, 3751, 3752, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3760, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3774, 3775, 3776, 3777, 3778, 3779, 3780, 3781, 3782, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, 3794, 3795, 3796, 3797, 3798, 3799, 3800, 3801, 3802, 3803, 3804, 3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3813, 3814, 3815, 3816, 3817, 3818, 3819, 3820, 3821, 3822, 3823, 3824, 3825, 3826, 3827, 3828, 3829, 3830, 3831, 3832, 3833, 3834, ...], 'Austria': [7588, 7589, 7590, 7591, 7592, 7593, 7594, 7595, 7596, 7597, 7598, 7599, 7600, 7601, 7602, 7603, 7604, 7605, 7606, 7607, 7608, 7609, 7610, 7611, 7612, 7613, 7614, 7615, 7616, 7617, 7618, 7619, 7620, 7621, 7622, 7623, 7624, 7625, 7626, 7627, 7628, 7629, 7630, 7631, 7632, 7633, 7634, 7635, 7636, 7637, 7638, 7639, 7640, 7641, 7642, 7643, 7644, 7645, 7646, 7647, 7648, 7649, 7650, 7651, 7652, 7653, 7654, 7655, 7656, 7657, 7658, 7659, 7660, 7661, 7662, 7663, 7664, 7665, 7666, 7667, 7668, 7669, 7670, 7671, 7672, 7673, 7674, 7675, 7676, 7677, 7678, 7679, 7680, 7681, 7682, 7683, 7684, 7685, 7686, 7687, ...], 'Belgium': [7270, 7271, 7272, 7273, 7274, 7275, 7276, 7277, 7278, 7279, 7280, 7281, 7282, 7283, 7284, 7285, 7286, 7287, 7288, 7289, 7290, 7291, 7292, 7293, 7294, 7295, 7296, 7297, 7298, 7299, 7300, 7301, 7302, 7303, 7304, 7305, 7306, 7307, 7308, 7309, 7310, 7311, 7312, 7313, 7314, 7315, 7316, 7317, 7318, 7319, 7320, 7321, 7322, 7323, 7324, 7325, 7326, 7327, 7328, 7329, 7330, 7331, 7332, 7333, 7334, 7335, 7336, 7337, 7338, 7339, 7340, 7341, 7342, 7343, 7344, 7345, 7346, 7347, 7348, 7349, 7350, 7351, 7352, 7353, 7354, 7355, 7356, 7357, 7358, 7359, 7360, 7361, 7362, 7363, 7364, 7365, 7366, 7367, 7368, 7369, ...], 'Brazil': [1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, ...], 'Canada': [864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, ...], 'China': [3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3482, 3483, 3484, 3485, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, ...], 'Denmark': [4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709, 4710, 4711, 4712, 4713, 4714, 4715, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4734, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754, 4755, 4756, 4757, 4758, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4771, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4789, 4790, 4791, 4792, 4793, 4794, ...], 'Finland': [4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4921, 4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932, 4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, ...], 'France': [5205, 5206, 5207, 5208, 5209, 5210, 5211, 5212, 5213, 5214, 5215, 5216, 5217, 5218, 5219, 5220, 5221, 5222, 5223, 5224, 5225, 5226, 5227, 5228, 5229, 5230, 5231, 5232, 5233, 5234, 5235, 5236, 5237, 5238, 5239, 5240, 5241, 5242, 5243, 5244, 5245, 5246, 5247, 5248, 5249, 5250, 5251, 5252, 5253, 5254, 5255, 5256, 5257, 5258, 5259, 5260, 5261, 5262, 5263, 5264, 5265, 5266, 5267, 5268, 5269, 5270, 5271, 5272, 5273, 5274, 5275, 5276, 5277, 5278, 5279, 5280, 5281, 5282, 5283, 5284, 5285, 5286, 5287, 5288, 5289, 5290, 5291, 5292, 5293, 5294, 5295, 5296, 5297, 5298, 5299, 5300, 5301, 5302, 5303, 5304, ...], 'Germany': [5807, 5808, 5809, 5810, 5811, 5812, 5813, 5814, 5815, 5816, 5817, 5818, 5819, 5820, 5821, 5822, 5823, 5824, 5825, 5826, 5827, 5828, 5829, 5830, 5831, 5832, 5833, 5834, 5835, 5836, 5837, 5838, 5839, 5840, 5841, 5842, 5843, 5844, 5845, 5846, 5847, 5848, 5849, 5850, 5851, 5852, 5853, 5854, 5855, 5856, 5857, 5858, 5859, 5860, 5861, 5862, 5863, 5864, 5865, 5866, 5867, 5868, 5869, 5870, 5871, 5872, 5873, 5874, 5875, 5876, 5877, 5878, 5879, 5880, 5881, 5882, 5883, 5884, 5885, 5886, 5887, 5888, 5889, 5890, 5891, 5892, 5893, 5894, 5895, 5896, 5897, 5898, 5899, 5900, 5901, 5902, 5903, 5904, 5905, 5906, ...], 'Italy': [7934, 7935, 7936, 7937, 7938, 7939, 7940, 7941, 7942, 7943, 7944, 7945, 7946, 7947, 7948, 7949, 7950, 7951, 7952, 7953, 7954, 7955, 7956, 7957, 7958, 7959, 7960, 7961, 7962, 7963, 7964, 7965, 7966, 7967, 7968, 7969, 7970, 7971, 7972, 7973, 7974, 7975, 7976, 7977, 7978, 7979, 7980, 7981, 7982, 7983, 7984, 7985, 7986, 7987, 7988, 7989, 7990, 7991, 7992, 7993, 7994, 7995, 7996, 7997, 7998, 7999, 8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009, 8010, 8011, 8012, 8013, 8014, 8015, 8016, 8017, 8018, 8019, 8020, 8021, 8022, 8023, 8024, 8025, 8026, 8027, 8028, 8029, 8030, 8031, 8032, 8033, ...], 'Japan': [2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, ...], 'Korea': [3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, ...], 'Mexico': [1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, ...], 'Netherlands': [4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4081, 4082, 4083, 4084, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4141, 4142, 4143, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158, 4159, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4168, 4169, 4170, 4171, ...], 'Singapore': [2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815, 2816, 2817, 2818, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, ...], 'Spain': [8310, 8311, 8312, 8313, 8314, 8315, 8316, 8317, 8318, 8319, 8320, 8321, 8322, 8323, 8324, 8325, 8326, 8327, 8328, 8329, 8330, 8331, 8332, 8333, 8334, 8335, 8336, 8337, 8338, 8339, 8340, 8341, 8342, 8343, 8344, 8345, 8346, 8347, 8348, 8349, 8350, 8351, 8352, 8353, 8354, 8355, 8356, 8357, 8358, 8359, 8360, 8361, 8362, 8363, 8364, 8365, 8366, 8367, 8368, 8369, 8370, 8371, 8372, 8373, 8374, 8375, 8376, 8377, 8378, 8379, 8380, 8381, 8382, 8383, 8384, 8385, 8386, 8387, 8388, 8389, 8390, 8391, 8392, 8393, 8394, 8395, 8396, 8397, 8398, 8399, 8400, 8401, 8402, 8403, 8404, 8405, 8406, 8407, 8408, 8409, ...], 'Sweden': [4453, 4454, 4455, 4456, 4457, 4458, 4459, 4460, 4461, 4462, 4463, 4464, 4465, 4466, 4467, 4468, 4469, 4470, 4471, 4472, 4473, 4474, 4475, 4476, 4477, 4478, 4479, 4480, 4481, 4482, 4483, 4484, 4485, 4486, 4487, 4488, 4489, 4490, 4491, 4492, 4493, 4494, 4495, 4496, 4497, 4498, 4499, 4500, 4501, 4502, 4503, 4504, 4505, 4506, 4507, 4508, 4509, 4510, 4511, 4512, 4513, 4514, 4515, 4516, 4517, 4518, 4519, 4520, 4521, 4522, 4523, 4524, 4525, 4526, 4527, 4528, 4529, 4530, 4531, 4532, 4533, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4541, 4542, 4543, 4544, 4545, 4546, 4547, 4548, 4549, 4550, 4551, 4552, ...], 'Switzerland': [6318, 6319, 6320, 6321, 6322, 6323, 6324, 6325, 6326, 6327, 6328, 6329, 6330, 6331, 6332, 6333, 6334, 6335, 6336, 6337, 6338, 6339, 6340, 6341, 6342, 6343, 6344, 6345, 6346, 6347, 6348, 6349, 6350, 6351, 6352, 6353, 6354, 6355, 6356, 6357, 6358, 6359, 6360, 6361, 6362, 6363, 6364, 6365, 6366, 6367, 6368, 6369, 6370, 6371, 6372, 6373, 6374, 6375, 6376, 6377, 6378, 6379, 6380, 6381, 6382, 6383, 6384, 6385, 6386, 6387, 6388, 6389, 6390, 6391, 6392, 6393, 6394, 6395, 6396, 6397, 6398, 6399, 6400, 6401, 6402, 6403, 6404, 6405, 6406, 6407, 6408, 6409, 6410, 6411, 6412, 6413, 6414, 6415, 6416, 6417, ...], 'United Kingdom': [6696, 6697, 6698, 6699, 6700, 6701, 6702, 6703, 6704, 6705, 6706, 6707, 6708, 6709, 6710, 6711, 6712, 6713, 6714, 6715, 6716, 6717, 6718, 6719, 6720, 6721, 6722, 6723, 6724, 6725, 6726, 6727, 6728, 6729, 6730, 6731, 6732, 6733, 6734, 6735, 6736, 6737, 6738, 6739, 6740, 6741, 6742, 6743, 6744, 6745, 6746, 6747, 6748, 6749, 6750, 6751, 6752, 6753, 6754, 6755, 6756, 6757, 6758, 6759, 6760, 6761, 6762, 6763, 6764, 6765, 6766, 6767, 6768, 6769, 6770, 6771, 6772, 6773, 6774, 6775, 6776, 6777, 6778, 6779, 6780, 6781, 6782, 6783, 6784, 6785, 6786, 6787, 6788, 6789, 6790, 6791, 6792, 6793, 6794, 6795, ...], 'United States': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]}

In [22]:
type(groups.groups)

pandas.io.formats.printing.PrettyDict

In [23]:
groups.groups['Belgium']

Int64Index([ 7270,  7271,  7272,  7273,  7274,  7275,  7276,  7277,  7278,
             7279,
            ...
            87859, 87860, 87861, 87862, 87863, 87864, 87865, 87866, 87867,
            87868],
           dtype='int64', length=3710)

In [24]:
type(groups.groups['Belgium'])

pandas.core.indexes.numeric.Int64Index

In [26]:
products.loc[groups.groups['Belgium']].head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
7270,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
7271,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Deluxe,2012,Q1 2012,5267.96,68,0.496579
7272,Belgium,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,22483.00,96,0.458979
7273,Belgium,Web,Golf Shop,Personal Accessories,Watches,TX,2012,Q1 2012,16100.00,87,0.448898
7274,Belgium,Web,Golf Shop,Personal Accessories,Eyewear,Polar Sun,2012,Q1 2012,2682.52,44,0.571075

In [27]:
groups.get_group('Belgium').head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
7270,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
7271,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Deluxe,2012,Q1 2012,5267.96,68,0.496579
7272,Belgium,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,22483.00,96,0.458979
7273,Belgium,Web,Golf Shop,Personal Accessories,Watches,TX,2012,Q1 2012,16100.00,87,0.448898
7274,Belgium,Web,Golf Shop,Personal Accessories,Eyewear,Polar Sun,2012,Q1 2012,2682.52,44,0.571075

## Aggregations

In [30]:
products = pd.read_csv('./course-files/course-sources/WA_Sales_Products_2012-14.csv')
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

### Standard aggregation methods
returns Data Frame with values for each column that values could be counted<br>
* `count()` counts not NaN values in each column
* `min()` and `max()` all columns
* `mean()` counts mean for numerical columns only

In [31]:
groups = products.groupby(by='Retailer country')
groups.mean().head()

                         Year       Revenue    Quantity  Gross margin
Retailer country
Australia         2012.859482  29822.638237  545.915689      0.451174
Austria           2012.875971  29354.380023  544.330917      0.450913
Belgium           2012.878976  26134.385420  484.911321      0.448410
Brazil            2012.878954  33170.824647  595.332117      0.448023
Canada            2012.839946  41682.874366  746.098936      0.451011

In [32]:
groups.sum().head()

                      Year       Revenue  Quantity  Gross margin
Retailer country
Australia          7377130  1.093000e+08   2000781   1641.822415
Austria            7773727  1.133666e+08   2102206   1723.839177
Belgium            7467781  9.695857e+07   1799021   1653.288385
Brazil             6618346  1.090657e+08   1957452   1466.380765
Canada            11922051  2.468877e+08   4419144   2662.767825

In [33]:
groups.count().head()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,3665,3665,3665,3665,3665,3665,3665,3665,3665,3639
Austria,3862,3862,3862,3862,3862,3862,3862,3862,3862,3823
Belgium,3710,3710,3710,3710,3710,3710,3710,3710,3710,3687
Brazil,3288,3288,3288,3288,3288,3288,3288,3288,3288,3273
Canada,5923,5923,5923,5923,5923,5923,5923,5923,5923,5904

In [34]:
groups.min().head()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,E-mail,Department Store,Camping Equipment,Binoculars,Aloe Relief,2012,Q1 2012,0.0,1,-0.389517
Austria,Sales visit,Department Store,Camping Equipment,Binoculars,Aloe Relief,2012,Q1 2012,0.0,4,-0.086616
Belgium,Fax,Department Store,Camping Equipment,Binoculars,Aloe Relief,2012,Q1 2012,0.0,5,-1.476136
Brazil,E-mail,Department Store,Camping Equipment,Binoculars,Aloe Relief,2012,Q1 2012,0.0,4,-2.085496
Canada,E-mail,Department Store,Camping Equipment,Binoculars,Aloe Relief,2012,Q1 2012,0.0,1,-1.373907

In [35]:
groups.max().head()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,Web,Warehouse Store,Personal Accessories,Woods,Zone,2014,Q4 2013,516135.14,20031,0.770476
Austria,Web,Warehouse Store,Personal Accessories,Woods,Zone,2014,Q4 2013,321202.98,9662,0.770476
Belgium,Web,Warehouse Store,Personal Accessories,Woods,Zone,2014,Q4 2013,310499.39,13200,0.770476
Brazil,Web,Warehouse Store,Personal Accessories,Woods,Zone,2014,Q4 2013,352749.39,12157,0.770476
Canada,Web,Warehouse Store,Personal Accessories,Woods,Zone,2014,Q4 2013,648467.60,27268,0.770476

In [41]:
products.loc[
    (products['Retailer country'] == 'Australia') &
    (products['Order method type'] == 'Web') &
    (products['Retailer type'] == 'Warehouse Store') &
    (products['Product line'] == 'Personal Accessories') &
    (products['Product type'] == 'Woods')
].head()

Empty DataFrame
Columns: [Retailer country, Order method type, Retailer type, Product line, Product type, Product, Year, Quarter, Revenue, Quantity, Gross margin]
Index: []

In [42]:
groups['Revenue'].sum().head()

Retailer country
Australia    1.093000e+08
Austria      1.133666e+08
Belgium      9.695857e+07
Brazil       1.090657e+08
Canada       2.468877e+08
Name: Revenue, dtype: float64

In [43]:
groups[['Revenue', 'Quantity']].mean().head()

                       Revenue    Quantity
Retailer country
Australia         29822.638237  545.915689
Austria           29354.380023  544.330917
Belgium           26134.385420  484.911321
Brazil            33170.824647  595.332117
Canada            41682.874366  746.098936

## Grouping and Multiindex

In [44]:
products = pd.read_csv('./course-files/course-sources/WA_Sales_Products_2012-14.csv')
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [46]:
groups = products.groupby(by=['Retailer country', 'Year'])
groups.size()  # how much transaction by a country and a year

Retailer country  Year
Australia         2012    1402
                  2013    1376
                  2014     887
Austria           2012    1436
                  2013    1469
                          ...
United Kingdom    2013    1845
                  2014    1258
United States     2012    3309
                  2013    2506
                  2014    1667
Length: 63, dtype: int64

In [49]:
# we have 3 times more groups beacause for each country we have 3 rows by each year
groups.sum().head(10)

                           Revenue  Quantity  Gross margin
Retailer country Year
Australia        2012  25607043.50    522186    625.835424
                 2013  47799737.14    839750    625.650690
                 2014  35893188.50    638845    390.336301
Austria          2012  34568089.63    702134    636.115492
                 2013  44996737.04    803771    665.086198
                 2014  33801788.98    596301    422.637486
Belgium          2012  30396297.49    635694    592.017290
                 2013  38375432.68    662157    667.302813
                 2014  28186839.74    501170    393.968282
Brazil           2012  34234876.30    688643    540.191035

In [54]:
groups.get_group(('Australia', 2012)).head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
3735,Australia,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2161.34,53,0.509564
3736,Australia,Telephone,Golf Shop,Personal Accessories,Binoculars,Seeker Mini,2012,Q1 2012,5689.60,70,0.507874
3737,Australia,Telephone,Golf Shop,Personal Accessories,Navigation,Glacier GPS,2012,Q1 2012,17337.34,158,0.284152
3738,Australia,Telephone,Golf Shop,Golf Equipment,Irons,Hailstorm Steel Irons,2012,Q1 2012,96118.50,255,0.413692
3739,Australia,Telephone,Golf Shop,Golf Equipment,Irons,Hailstorm Titanium Irons,2012,Q1 2012,40149.72,46,0.437513

## agg() method

In [55]:
products = pd.read_csv('./course-files/course-sources/WA_Sales_Products_2012-14.csv')
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [56]:
groups = products.groupby(by=['Retailer country', 'Year'])
groups['Revenue'].sum().head()

Retailer country  Year
Australia         2012    25607043.50
                  2013    47799737.14
                  2014    35893188.50
Austria           2012    34568089.63
                  2013    44996737.04
Name: Revenue, dtype: float64

In [57]:
groups[['Quantity', 'Revenue']].sum().head()

                       Quantity      Revenue
Retailer country Year
Australia        2012    522186  25607043.50
                 2013    839750  47799737.14
                 2014    638845  35893188.50
Austria          2012    702134  34568089.63
                 2013    803771  44996737.04

In [58]:
groups['Gross margin'].mean().head()

Retailer country  Year
Australia         2012    0.447985
                  2013    0.457347
                  2014    0.446609
Austria           2012    0.446084
                  2013    0.456790
Name: Gross margin, dtype: float64

In [59]:
groups.Revenue.sum().head()

Retailer country  Year
Australia         2012    25607043.50
                  2013    47799737.14
                  2014    35893188.50
Austria           2012    34568089.63
                  2013    44996737.04
Name: Revenue, dtype: float64

In [60]:
groups.Quantity.sum().head()

Retailer country  Year
Australia         2012    522186
                  2013    839750
                  2014    638845
Austria           2012    702134
                  2013    803771
Name: Quantity, dtype: int64

In [62]:
groups.agg(dict(Revenue=sum)).head()

                           Revenue
Retailer country Year
Australia        2012  25607043.50
                 2013  47799737.14
                 2014  35893188.50
Austria          2012  34568089.63
                 2013  44996737.04

In [65]:
groups.agg({'Gross margin': 'mean'}).head()

                       Gross margin
Retailer country Year
Australia        2012      0.447985
                 2013      0.457347
                 2014      0.446609
Austria          2012      0.446084
                 2013      0.456790

In [67]:
groups.agg(
    {
        "Revenue": sum,
        'Quantity': 'sum',
        'Gross margin': 'mean'
    }
).head()

                           Revenue  Quantity  Gross margin
Retailer country Year
Australia        2012  25607043.50    522186      0.447985
                 2013  47799737.14    839750      0.457347
                 2014  35893188.50    638845      0.446609
Austria          2012  34568089.63    702134      0.446084
                 2013  44996737.04    803771      0.456790

In [68]:
groups.agg(
    {
        "Revenue": [sum, min, max],
        'Quantity': 'sum',
        'Gross margin': 'mean'
    }
).head()

                           Revenue                 Quantity Gross margin
                               sum  min        max      sum         mean
Retailer country Year
Australia        2012  25607043.50  0.0  254026.08   522186     0.447985
                 2013  47799737.14  0.0  443746.60   839750     0.457347
                 2014  35893188.50  0.0  516135.14   638845     0.446609
Austria          2012  34568089.63  0.0  199715.40   702134     0.446084
                 2013  44996737.04  0.0  317161.24   803771     0.456790

In [71]:
groups.agg(
    {
        "Revenue": ['sum'],
        'Quantity': 'sum',
        'Gross margin': 'mean'
    }
).head()

                           Revenue Quantity Gross margin
                               sum      sum         mean
Retailer country Year
Australia        2012  25607043.50   522186     0.447985
                 2013  47799737.14   839750     0.457347
                 2014  35893188.50   638845     0.446609
Austria          2012  34568089.63   702134     0.446084
                 2013  44996737.04   803771     0.456790

## Data processing from an group object

In [72]:
products = pd.read_csv('./course-files/course-sources/WA_Sales_Products_2012-14.csv')
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [78]:
groups = products.groupby(by='Retailer country')

### `Items` in Groups

In [117]:
abbc = dict(a=1,b=2,c=3)
print(abbc.keys())
print(abbc.values())
print(abbc.items())

for el in abbc:
    print(f'{el = }\t{abbc[el] = }')

# by 2 variables like in Groovy, it doesn't work :(
# for ke, va in abbc:
#     print(ke, va)

dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])
el = 'a'	abbc[el] = 1
el = 'b'	abbc[el] = 2
el = 'c'	abbc[el] = 3

Each element in a group is an element of a dict.<br>The element contains a tuple with 2 value:
* a key
* the value of a key.

#### `Keys` in groups

In [108]:
for country in groups:
    print(country[0], type(country), len(country), sep='\t')

Australia	<class 'tuple'>	2
Austria	<class 'tuple'>	2
Belgium	<class 'tuple'>	2
Brazil	<class 'tuple'>	2
Canada	<class 'tuple'>	2
China	<class 'tuple'>	2
Denmark	<class 'tuple'>	2
Finland	<class 'tuple'>	2
France	<class 'tuple'>	2
Germany	<class 'tuple'>	2
Italy	<class 'tuple'>	2
Japan	<class 'tuple'>	2
Korea	<class 'tuple'>	2
Mexico	<class 'tuple'>	2
Netherlands	<class 'tuple'>	2
Singapore	<class 'tuple'>	2
Spain	<class 'tuple'>	2
Sweden	<class 'tuple'>	2
Switzerland	<class 'tuple'>	2
United Kingdom	<class 'tuple'>	2
United States	<class 'tuple'>	2

In [109]:
country_names = list()
for country in groups:
    country_names.append(country[0])
country_names

['Australia',
 'Austria',
 'Belgium',
 'Brazil',
 'Canada',
 'China',
 'Denmark',
 'Finland',
 'France',
 'Germany',
 'Italy',
 'Japan',
 'Korea',
 'Mexico',
 'Netherlands',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'United Kingdom',
 'United States']

#### `Values` in groups

In [110]:
for country in groups:
    print(country[1])

      Retailer country Order method type     Retailer type  \
3735         Australia         Telephone         Golf Shop
3736         Australia         Telephone         Golf Shop
3737         Australia         Telephone         Golf Shop
3738         Australia         Telephone         Golf Shop
3739         Australia         Telephone         Golf Shop
...                ...               ...               ...
85862        Australia       Sales visit  Department Store
85863        Australia       Sales visit  Department Store
85864        Australia       Sales visit  Department Store
85865        Australia       Sales visit  Department Store
85866        Australia       Sales visit  Department Store

               Product line Product type                   Product  Year  \
3735   Personal Accessories      Watches      Mountain Man Digital  2012
3736   Personal Accessories   Binoculars               Seeker Mini  2012
3737   Personal Accessories   Navigation               Glacier GPS  2012
3738         Golf Equipment        Irons     Hailstorm Steel Irons  2012
3739         Golf Equipment        Irons  Hailstorm Titanium Irons  2012
...                     ...          ...                       ...   ...
85862  Personal Accessories      Watches      Mountain Man Digital  2014
85863  Personal Accessories      Watches       Mountain Man Deluxe  2014
85864  Personal Accessories      Watches  Mountain Man Combination  2014
85865  Personal Accessories   Navigation             Glacier Basic  2014
85866        Golf Equipment      Putters         Blue Steel Putter  2014

       Quarter   Revenue  Quantity  Gross margin
3735   Q1 2012   2161.34        53      0.509564
3736   Q1 2012   5689.60        70      0.507874
3737   Q1 2012  17337.34       158      0.284152
3738   Q1 2012  96118.50       255      0.413692
3739   Q1 2012  40149.72        46      0.437513
...        ...       ...       ...           ...
85862  Q3 2014   5627.64       138      0.509564
85863  Q3 2014   7049.77        91      0.496579
85864  Q3 2014   4034.10        42      0.531494
85865  Q3 2014  36945.36      1164      0.369880
85866  Q3 2014  14248.39       169      0.511327

[3665 rows x 11 columns]
      Retailer country Order method type Retailer type          Product line  \
7588           Austria         Telephone     Golf Shop  Personal Accessories
7589           Austria         Telephone     Golf Shop  Personal Accessories
7590           Austria         Telephone     Golf Shop  Personal Accessories
7591           Austria         Telephone     Golf Shop  Personal Accessories
7592           Austria         Telephone     Golf Shop  Personal Accessories
...                ...               ...           ...                   ...
88078          Austria               Web  Sports Store        Golf Equipment
88079          Austria               Web  Sports Store        Golf Equipment
88080          Austria               Web  Sports Store        Golf Equipment
88081          Austria               Web  Sports Store        Golf Equipment
88082          Austria               Web  Sports Store        Golf Equipment

           Product type                Product  Year  Quarter   Revenue  \
7588            Watches    Mountain Man Analog  2012  Q1 2012   6562.30
7589            Eyewear              Polar Sun  2012  Q1 2012   4599.56
7590            Eyewear              Polar Ice  2012  Q1 2012   3553.00
7591            Eyewear             Polar Wave  2012  Q1 2012   1051.82
7592         Binoculars              Seeker 35  2012  Q1 2012  13657.86
...                 ...                    ...   ...      ...       ...
88078           Putters      Blue Steel Putter  2014  Q3 2014  12815.12
88079           Putters  Blue Steel Max Putter  2014  Q3 2014  28142.40
88080  Golf Accessories    Course Pro Umbrella  2014  Q3 2014  12487.25
88081  Golf Accessories    Course Pro Golf Bag  2014  Q3 2014  20000.64
88082  Golf Accessories      Course Pro Gloves  2014  Q3 2014  11759.84

       Quantity  Gross margin
7588        137      0.373695
7589         75      0.573601
7590         34      0.524498
7591         11      0.569964
7592        138      0.280691
...         ...           ...
88078       152      0.511327
88079       164      0.523310
88080       995      0.484462
88081        96      0.617452
88082      2194      0.524254

[3862 rows x 11 columns]
      Retailer country Order method type Retailer type          Product line  \
7270           Belgium               Web     Golf Shop  Personal Accessories
7271           Belgium               Web     Golf Shop  Personal Accessories
7272           Belgium               Web     Golf Shop  Personal Accessories
7273           Belgium               Web     Golf Shop  Personal Accessories
7274           Belgium               Web     Golf Shop  Personal Accessories
...                ...               ...           ...                   ...
87864          Belgium               Web  Sports Store  Personal Accessories
87865          Belgium               Web  Sports Store  Personal Accessories
87866          Belgium               Web  Sports Store  Personal Accessories
87867          Belgium               Web  Sports Store  Personal Accessories
87868          Belgium               Web  Sports Store  Personal Accessories

      Product type               Product  Year  Quarter   Revenue  Quantity  \
7270       Watches  Mountain Man Digital  2012  Q1 2012   2324.46        57
7271       Watches   Mountain Man Deluxe  2012  Q1 2012   5267.96        68
7272       Watches              Infinity  2012  Q1 2012  22483.00        96
7273       Watches                    TX  2012  Q1 2012  16100.00        87
7274       Eyewear             Polar Sun  2012  Q1 2012   2682.52        44
...            ...                   ...   ...      ...       ...       ...
87864       Knives             Max Gizmo  2014  Q3 2014   8803.80       219
87865   Binoculars             Seeker 50  2014  Q3 2014  16689.40       131
87866   Binoculars        Seeker Extreme  2014  Q3 2014  18048.16       104
87867   Binoculars         Ranger Vision  2014  Q3 2014   3380.00        20
87868   Navigation           Astro Pilot  2014  Q3 2014  33294.00        93

       Gross margin
7270       0.509564
7271       0.496579
7272       0.458979
7273       0.448898
7274       0.571075
...             ...
87864      0.536567
87865      0.273312
87866      0.457647
87867      0.533432
87868      0.350754

[3710 rows x 11 columns]
      Retailer country Order method type Retailer type          Product line  \
1833            Brazil               Web     Golf Shop  Personal Accessories
1834            Brazil               Web     Golf Shop  Personal Accessories
1835            Brazil               Web     Golf Shop  Personal Accessories
1836            Brazil               Web     Golf Shop  Personal Accessories
1837            Brazil               Web     Golf Shop  Personal Accessories
...                ...               ...           ...                   ...
84734           Brazil               Web  Sports Store        Golf Equipment
84735           Brazil               Web  Sports Store        Golf Equipment
84736           Brazil               Web  Sports Store        Golf Equipment
84737           Brazil               Web  Sports Store        Golf Equipment
84738           Brazil               Web  Sports Store        Golf Equipment

           Product type                Product  Year  Quarter   Revenue  \
1833            Watches                  Venue  2012  Q1 2012  15987.00
1834            Watches                    Lux  2012  Q1 2012   7189.60
1835            Watches                    Sam  2012  Q1 2012   8890.20
1836            Watches                     TX  2012  Q1 2012  17816.00
1837            Watches                 Kodiak  2012  Q1 2012   7218.00
...                 ...                    ...   ...      ...       ...
84734           Putters      Blue Steel Putter  2014  Q3 2014  12309.26
84735           Putters  Blue Steel Max Putter  2014  Q3 2014  23509.20
84736  Golf Accessories    Course Pro Umbrella  2014  Q3 2014  10391.40
84737  Golf Accessories    Course Pro Golf Bag  2014  Q3 2014  18750.60
84738  Golf Accessories      Course Pro Gloves  2014  Q3 2014   8066.80

       Quantity  Gross margin
1833        219      0.419206
1834         43      0.478828
1835        198      0.388419
1836         93      0.458950
1837         60      0.444223
...         ...           ...
84734       146      0.511327
84735       137      0.523310
84736       828      0.484462
84737        90      0.617452
84738      1505      0.524254

[3288 rows x 11 columns]
      Retailer country Order method type  Retailer type          Product line  \
864             Canada               Fax  Outdoors Shop  Personal Accessories
865             Canada               Fax  Outdoors Shop  Personal Accessories
866             Canada               Fax  Outdoors Shop  Personal Accessories
867             Canada               Fax  Outdoors Shop  Personal Accessories
868             Canada               Fax  Outdoors Shop  Personal Accessories
...                ...               ...            ...                   ...
84363           Canada               Web   Sports Store        Golf Equipment
84364           Canada               Web   Sports Store        Golf Equipment
84365           Canada               Web   Sports Store        Golf Equipment
84366           Canada               Web   Sports Store        Golf Equipment
84367           Canada               Web   Sports Store        Golf Equipment

           Product type                Product  Year  Quarter   Revenue  \
864             Watches                  Venue  2012  Q1 2012  12045.00
865             Watches                     TX  2012  Q1 2012  20960.00
866             Watches                 Legend  2012  Q1 2012   3740.00
867             Watches                 Kodiak  2012  Q1 2012  33445.20
868             Eyewear                  Capri  2012  Q1 2012  23784.30
...                 ...                    ...   ...      ...       ...
84363           Putters      Course Pro Putter  2014  Q3 2014  68133.45
84364           Putters  Blue Steel Max Putter  2014  Q3 2014  37408.80
84365  Golf Accessories    Course Pro Umbrella  2014  Q3 2014  14356.65
84366  Golf Accessories    Course Pro Golf Bag  2014  Q3 2014  24167.44
84367  Golf Accessories      Course Pro Gloves  2014  Q3 2014  13753.76

       Quantity  Gross margin
864         165      0.418630
865         114      0.450544
866          17      0.473455
867         271      0.455317
868         621      0.340707
...         ...           ...
84363      1735      0.385281
84364       218      0.523310
84365      1155      0.479485
84366       116      0.617452
84367      2566      0.524254

[5923 rows x 11 columns]
      Retailer country Order method type Retailer type        Product line  \
3403             China               Fax     Golf Shop      Golf Equipment
3404             China               Fax     Golf Shop      Golf Equipment
3405             China               Fax     Golf Shop      Golf Equipment
3406             China               Fax     Golf Shop      Golf Equipment
3407             China               Fax     Golf Shop      Golf Equipment
...                ...               ...           ...                 ...
85667            China               Web  Sports Store  Outdoor Protection
85668            China               Web  Sports Store  Outdoor Protection
85669            China               Web  Sports Store  Outdoor Protection
85670            China               Web  Sports Store  Outdoor Protection
85671            China               Web  Sports Store  Outdoor Protection

            Product type                     Product  Year  Quarter  \
3403               Irons       Hailstorm Steel Irons  2012  Q1 2012
3404               Irons  Lady Hailstorm Steel Irons  2012  Q1 2012
3405               Woods   Hailstorm Steel Woods Set  2012  Q1 2012
3406             Putters           Blue Steel Putter  2012  Q1 2012
3407    Golf Accessories         Course Pro Umbrella  2012  Q1 2012
...                  ...                         ...   ...      ...
85667  Insect Repellents            BugShield Lotion  2014  Q3 2014
85668          Sunscreen                 Sun Blocker  2014  Q3 2014
85669          Sunscreen              Sun Shelter 15  2014  Q3 2014
85670          Sunscreen              Sun Shelter 30  2014  Q3 2014
85671          First Aid             Calamine Relief  2014  Q3 2014

         Revenue  Quantity  Gross margin
3403    69057.80       214      0.315153
3404    57590.85       115      0.445356
3405   198666.24       290      0.501355
3406    18992.50       214      0.535775
3407    19082.56      1568      0.506984
...          ...       ...           ...
85667    3381.00       483      0.667143
85668    1625.00       325      0.610000
85669    2519.40       510      0.637652
85670    4944.10      1009      0.622449
85671     408.00        68      0.528333

[3652 rows x 11 columns]
      Retailer country Order method type Retailer type          Product line  \
4695           Denmark               Web     Golf Shop  Personal Accessories
4696           Denmark               Web     Golf Shop  Personal Accessories
4697           Denmark               Web     Golf Shop  Personal Accessories
4698           Denmark               Web     Golf Shop  Personal Accessories
4699           Denmark               Web     Golf Shop  Personal Accessories
...                ...               ...           ...                   ...
86355          Denmark               Web  Sports Store  Personal Accessories
86356          Denmark               Web  Sports Store  Personal Accessories
86357          Denmark               Web  Sports Store  Personal Accessories
86358          Denmark               Web  Sports Store  Personal Accessories
86359          Denmark               Web  Sports Store  Personal Accessories

      Product type        Product  Year  Quarter   Revenue  Quantity  \
4695       Watches          Venue  2012  Q1 2012   2482.00        34
4696       Watches       Infinity  2012  Q1 2012   4180.00        19
4697       Watches            Lux  2012  Q1 2012   5208.40        29
4698       Watches            Sam  2012  Q1 2012   4130.80        92
4699       Watches             TX  2012  Q1 2012  15228.00        81
...            ...            ...   ...      ...       ...       ...
86355      Eyewear        Fairway  2014  Q3 2014   1466.25        69
86356      Eyewear        Inferno  2014  Q3 2014  11947.50       177
86357      Eyewear           Zone  2014  Q3 2014   3521.70       101
86358      Eyewear          Retro  2014  Q3 2014  12404.70       198
86359   Binoculars  Ranger Vision  2014  Q3 2014   8788.00        52

       Gross margin
4695       0.418630
4696       0.474727
4697       0.471715
4698       0.391537
4699       0.445985
...             ...
86355      0.416471
86356      0.468593
86357      0.356765
86358      0.463847
86359      0.533432

[2358 rows x 11 columns]
      Retailer country Order method type     Retailer type       Product line  \
4913           Finland               Web  Department Store  Camping Equipment
4914           Finland               Web  Department Store  Camping Equipment
4915           Finland               Web  Department Store  Camping Equipment
4916           Finland               Web  Department Store  Camping Equipment
4917           Finland               Web  Department Store  Camping Equipment
...                ...               ...               ...                ...
86546          Finland               Web      Sports Store     Golf Equipment
86547          Finland               Web      Sports Store     Golf Equipment
86548          Finland               Web      Sports Store     Golf Equipment
86549          Finland               Web      Sports Store     Golf Equipment
86550          Finland               Web      Sports Store     Golf Equipment

           Product type                      Product  Year  Quarter   Revenue  \
4913       Cooking Gear          TrailChef Water Bag  2012  Q1 2012  16007.34
4914       Cooking Gear            TrailChef Canteen  2012  Q1 2012  10567.85
4915       Cooking Gear        TrailChef Kitchen Kit  2012  Q1 2012  20319.20
4916       Cooking Gear           TrailChef Cook Set  2012  Q1 2012  41867.62
4917       Cooking Gear             TrailChef Kettle  2012  Q1 2012  73606.26
...                 ...                          ...   ...      ...       ...
86546           Putters        Blue Steel Max Putter  2014  Q3 2014  48562.80
86547  Golf Accessories  Course Pro Golf and Tee Set  2014  Q3 2014  12703.92
86548  Golf Accessories          Course Pro Umbrella  2014  Q3 2014  14953.29
86549  Golf Accessories          Course Pro Golf Bag  2014  Q3 2014  25417.48
86550  Golf Accessories            Course Pro Gloves  2014  Q3 2014  14380.88

       Quantity  Gross margin
4913       2586      0.526656
4914       1205      0.496009
4915        880      0.310091
4916        794      0.336810
4917       9282      0.496847
...         ...           ...
86546       283      0.523310
86547      1231      0.670543
86548      1203      0.479485
86549       122      0.617452
86550      2683      0.524254

[3409 rows x 11 columns]
      Retailer country Order method type Retailer type       Product line  \
5205            France               Fax     Golf Shop     Golf Equipment
5206            France               Fax     Golf Shop     Golf Equipment
5207            France               Fax     Golf Shop     Golf Equipment
5208            France               Fax  Sports Store  Camping Equipment
5209            France               Fax  Sports Store  Camping Equipment
...                ...               ...           ...                ...
86854           France       Sales visit  Sports Store     Golf Equipment
86855           France       Sales visit  Sports Store     Golf Equipment
86856           France       Sales visit  Sports Store     Golf Equipment
86857           France       Sales visit  Sports Store     Golf Equipment
86858           France       Sales visit  Sports Store     Golf Equipment

           Product type                        Product  Year  Quarter  \
5205              Irons     Lady Hailstorm Steel Irons  2012  Q1 2012
5206              Irons  Lady Hailstorm Titanium Irons  2012  Q1 2012
5207            Putters          Blue Steel Max Putter  2012  Q1 2012
5208       Cooking Gear            TrailChef Water Bag  2012  Q1 2012
5209       Cooking Gear              TrailChef Canteen  2012  Q1 2012
...                 ...                            ...   ...      ...
86854           Putters              Blue Steel Putter  2014  Q3 2014
86855           Putters          Blue Steel Max Putter  2014  Q3 2014
86856  Golf Accessories            Course Pro Umbrella  2014  Q3 2014
86857  Golf Accessories            Course Pro Golf Bag  2014  Q3 2014
86858  Golf Accessories              Course Pro Gloves  2014  Q3 2014

        Revenue  Quantity  Gross margin
5205   19530.81        39      0.445356
5206   39276.96        47      0.449550
5207   22921.65       135      0.459332
5208   32137.20      8136      0.465823
5209    9480.37      1081      0.496009
...         ...       ...           ...
86854  16862.00       200      0.511327
86855  33976.80       198      0.523310
86856  10466.70       834      0.484462
86857  17708.90        85      0.617452
86858  10001.76      1866      0.524254

[5779 rows x 11 columns]
      Retailer country Order method type    Retailer type       Product line  \
5807           Germany              Mail  Warehouse Store  Camping Equipment
5808           Germany              Mail  Warehouse Store  Camping Equipment
5809           Germany              Mail  Warehouse Store  Camping Equipment

      Retailer country Order method type  Retailer type          Product line  \
2750         Singapore               Fax  Outdoors Shop     Camping Equipment
2751         Singapore               Fax  Outdoors Shop     Camping Equipment
2752         Singapore               Fax  Outdoors Shop     Camping Equipment
2753         Singapore               Fax  Outdoors Shop     Camping Equipment
2754         Singapore               Fax  Outdoors Shop     Camping Equipment
...                ...               ...            ...                   ...
85255        Singapore               Web  Outdoors Shop  Personal Accessories
85256        Singapore               Web  Outdoors Shop  Personal Accessories
85257        Singapore               Web  Outdoors Shop  Personal Accessories
85258        Singapore               Web  Outdoors Shop  Personal Accessories
85259        Singapore               Web  Outdoors Shop  Personal Accessories

        Product type                       Product  Year  Quarter   Revenue  \
2750    Cooking Gear            TrailChef Cook Set  2012  Q1 2012  49777.12
2751   Sleeping Bags             Hibernator Pillow  2012  Q1 2012   6539.40
2752           Packs  Canyon Mule Climber Backpack  2012  Q1 2012  30995.25
2753        Lanterns           Firefly Multi-light  2012  Q1 2012   6502.50
2754        Lanterns               EverGlow Butane  2012  Q1 2012   6558.01
...              ...                           ...   ...      ...       ...
85255     Binoculars                 Ranger Vision  2014  Q3 2014  56666.50
85256     Navigation                Glacier Deluxe  2014  Q3 2014  22263.66
85257     Navigation           Glacier GPS Extreme  2014  Q3 2014  75839.64
85258     Navigation                   Astro Pilot  2014  Q3 2014  53919.00
85259     Navigation                     Sky Pilot  2014  Q3 2014  10024.00

       Quantity  Gross margin
2750        944      0.336810
2751        378      0.529480
2752        429      0.273356
2753        250      0.316417
2754        103      0.361866
...         ...           ...
85255       337      0.533432
85256       243      0.443353
85257       222      0.483432
85258       294      0.371835
85259        28      0.358715

[3443 rows x 11 columns]
      Retailer country Order method type  Retailer type  \
8310             Spain               Fax   Sports Store
8311             Spain               Fax   Sports Store
8312             Spain               Fax   Sports Store
8313             Spain               Fax   Sports Store
8314             Spain               Fax   Sports Store
...                ...               ...            ...
88470            Spain       Sales visit  Outdoors Shop
88471            Spain       Sales visit  Outdoors Shop
88472            Spain       Sales visit  Outdoors Shop
88473            Spain       Sales visit  Outdoors Shop
88474            Spain       Sales visit  Outdoors Shop

                   Product line          Product type                Product  \
8310          Camping Equipment          Cooking Gear    TrailChef Water Bag
8311          Camping Equipment          Cooking Gear          TrailChef Cup
8312          Camping Equipment         Sleeping Bags             Hibernator
8313       Personal Accessories               Watches    Mountain Man Analog
8314       Personal Accessories               Eyewear              Polar Sun
...                         ...                   ...                    ...
88470  Mountaineering Equipment                  Rope          Husky Rope 60
88471  Mountaineering Equipment  Climbing Accessories  Firefly Climbing Lamp
88472  Mountaineering Equipment  Climbing Accessories        Firefly Charger
88473  Mountaineering Equipment                 Tools            Granite Axe
88474  Mountaineering Equipment                 Tools        Granite Extreme

       Year  Quarter   Revenue  Quantity  Gross margin
8310   2012  Q1 2012  12191.58      1926      0.537125
8311   2012  Q1 2012   2994.06       834      0.763231
8312   2012  Q1 2012  31882.62       231      0.376902
8313   2012  Q1 2012   2442.90        51      0.373695
8314   2012  Q1 2012   1360.48        22      0.577135
...     ...      ...       ...       ...           ...
88470  2014  Q3 2014  30865.50       171      0.299114
88471  2014  Q3 2014   7485.29       191      0.446287
88472  2014  Q3 2014  12255.48       236      0.569420
88473  2014  Q3 2014  56448.00      1470      0.491667
88474  2014  Q3 2014  89376.00      1176      0.387895

[3557 rows x 11 columns]
      Retailer country Order method type  Retailer type        Product line  \
4453            Sweden            E-mail  Outdoors Shop   Camping Equipment
4454            Sweden            E-mail  Outdoors Shop   Camping Equipment
4455            Sweden            E-mail  Outdoors Shop   Camping Equipment
4456            Sweden            E-mail  Outdoors Shop   Camping Equipment
4457            Sweden            E-mail  Outdoors Shop   Camping Equipment
...                ...               ...            ...                 ...
86258           Sweden       Sales visit   Sports Store   Camping Equipment
86259           Sweden       Sales visit   Sports Store   Camping Equipment
86260           Sweden       Sales visit   Sports Store  Outdoor Protection
86261           Sweden       Sales visit   Sports Store      Golf Equipment
86262           Sweden       Sales visit   Sports Store      Golf Equipment

           Product type                Product  Year  Quarter   Revenue  \
4453       Cooking Gear       TrailChef Kettle  2012  Q1 2012  12371.30
4454              Tents           Star Gazer 2  2012  Q1 2012  82120.50
4455      Sleeping Bags        Hibernator Lite  2012  Q1 2012  29129.92
4456      Sleeping Bags     Hibernator Extreme  2012  Q1 2012  35889.12
4457      Sleeping Bags    Hibernator Camp Cot  2012  Q1 2012  14829.71
...                 ...                    ...   ...      ...       ...
86258          Lanterns        EverGlow Double  2014  Q3 2014   1929.55
86259          Lanterns      EverGlow Kerosene  2014  Q3 2014   7635.10
86260         Sunscreen         Sun Shelter 15  2014  Q3 2014   1215.24
86261             Irons  Hailstorm Steel Irons  2014  Q3 2014  50802.20
86262  Golf Accessories      Course Pro Gloves  2014  Q3 2014   6399.84

       Quantity  Gross margin
4453        965      0.601404
4454        150      0.282938
4455        344      0.291450
4456        144      0.398146
4457        151      0.335607
...         ...           ...
86258        37      0.448706
86259       242      0.366086
86260       246      0.637652
86261       116      0.495376
86262      1194      0.524254

[2925 rows x 11 columns]
      Retailer country Order method type Retailer type          Product line  \
6318       Switzerland               Fax     Golf Shop  Personal Accessories
6319       Switzerland               Fax     Golf Shop  Personal Accessories
6320       Switzerland               Fax     Golf Shop  Personal Accessories
6321       Switzerland               Fax     Golf Shop  Personal Accessories
6322       Switzerland               Fax     Golf Shop  Personal Accessories
...                ...               ...           ...                   ...
87385      Switzerland               Web  Sports Store        Golf Equipment
87386      Switzerland               Web  Sports Store        Golf Equipment
87387      Switzerland               Web  Sports Store        Golf Equipment
87388      Switzerland               Web  Sports Store        Golf Equipment
87389      Switzerland               Web  Sports Store        Golf Equipment

           Product type                Product  Year  Quarter   Revenue  \
6318            Watches               Infinity  2012  Q1 2012   5500.00
6319            Watches                    Lux  2012  Q1 2012   5388.00
6320            Watches                    Sam  2012  Q1 2012   5657.40
6321            Watches                     TX  2012  Q1 2012  15792.00
6322            Watches                 Legend  2012  Q1 2012   5404.00
...                 ...                    ...   ...      ...       ...
87385           Putters      Course Pro Putter  2014  Q3 2014  50736.84
87386           Putters  Blue Steel Max Putter  2014  Q3 2014  28485.60
87387  Golf Accessories    Course Pro Umbrella  2014  Q3 2014   8935.60
87388  Golf Accessories    Course Pro Golf Bag  2014  Q3 2014  15000.48
87389  Golf Accessories      Course Pro Gloves  2014  Q3 2014   8425.92

       Quantity  Gross margin
6318         25      0.473455
6319         30      0.471715
6320        126      0.391537
6321         84      0.448412
6322         20      0.444782
...         ...           ...
87385      1292      0.385281
87386       166      0.523310
87387       712      0.484462
87388        72      0.617452
87389      1572      0.524254

[4103 rows x 11 columns]
      Retailer country Order method type  Retailer type          Product line  \
6696    United Kingdom               Fax  Outdoors Shop  Personal Accessories
6697    United Kingdom               Fax  Outdoors Shop  Personal Accessories
6698    United Kingdom               Fax  Outdoors Shop  Personal Accessories
6699    United Kingdom               Fax  Outdoors Shop  Personal Accessories
6700    United Kingdom               Fax  Outdoors Shop  Personal Accessories
...                ...               ...            ...                   ...
87672   United Kingdom       Sales visit  Outdoors Shop  Personal Accessories
87673   United Kingdom       Sales visit  Outdoors Shop  Personal Accessories
87674   United Kingdom       Sales visit  Outdoors Shop  Personal Accessories
87675   United Kingdom       Sales visit  Outdoors Shop  Personal Accessories
87676   United Kingdom       Sales visit  Outdoors Shop  Personal Accessories

      Product type               Product  Year  Quarter   Revenue  Quantity  \
6696       Watches                 Venue  2012  Q1 2012  41205.00       570
6697       Watches                   Lux  2012  Q1 2012  29366.40       170
6698       Watches                    TX  2012  Q1 2012  23312.00       124
6699       Watches                Legend  2012  Q1 2012  11540.00        51
6700       Eyewear                 Bella  2012  Q1 2012   9900.00       132
...            ...                   ...   ...      ...       ...       ...
87672      Watches  Mountain Man Extreme  2014  Q3 2014   5192.82        18
87673       Knives           Single Edge  2014  Q3 2014  33639.94      2771
87674       Knives          Edge Extreme  2014  Q3 2014  25812.17       227
87675   Navigation        Glacier Deluxe  2014  Q3 2014  15392.16       168
87676   Navigation   Glacier GPS Extreme  2014  Q3 2014  45093.84       132

       Gross margin
6696       0.419461
6697       0.474224
6698       0.448247
6699       0.466953
6700       0.417333
...             ...
87672      0.597248
87673      0.294893
87674      0.296456
87675      0.443353
87676      0.483432

[5102 rows x 11 columns]
      Retailer country Order method type  Retailer type          Product line  \
0        United States               Fax  Outdoors Shop     Camping Equipment
1        United States               Fax  Outdoors Shop     Camping Equipment
2        United States               Fax  Outdoors Shop     Camping Equipment
3        United States               Fax  Outdoors Shop     Camping Equipment
4        United States               Fax  Outdoors Shop     Camping Equipment
...                ...               ...            ...                   ...
84049    United States       Sales visit  Eyewear Store  Personal Accessories
84050    United States       Sales visit  Eyewear Store  Personal Accessories
84051    United States       Sales visit  Eyewear Store  Personal Accessories
84052    United States       Sales visit  Eyewear Store  Personal Accessories
84053    United States       Sales visit  Eyewear Store  Personal Accessories

        Product type                    Product  Year  Quarter    Revenue  \
0       Cooking Gear  TrailChef Deluxe Cook Set  2012  Q1 2012   59628.66
1       Cooking Gear     TrailChef Double Flame  2012  Q1 2012   35950.32
2              Tents                  Star Dome  2012  Q1 2012   89940.48
3              Tents               Star Gazer 2  2012  Q1 2012  165883.41
4      Sleeping Bags            Hibernator Lite  2012  Q1 2012  119822.20
...              ...                        ...   ...      ...        ...
84049        Eyewear                  Polar Ice  2014  Q3 2014   20957.00
84050        Eyewear               Polar Sports  2014  Q3 2014  105495.85
84051        Eyewear                 Polar Wave  2014  Q3 2014    6540.48
84052        Eyewear              Polar Extreme  2014  Q3 2014    6340.05
84053     Binoculars                  Seeker 35  2014  Q3 2014   83324.99

       Quantity  Gross margin
0           489      0.347548
1           252      0.474274
2           147      0.352772
3           303      0.282938
4          1415      0.291450
...         ...           ...
84049       218      0.483112
84050       905      0.494896
84051        72      0.547336
84052        45      0.485414
84053       833      0.288314

[7482 rows x 11 columns]

In [111]:
for country in groups:
    print(country[0], len(country[1]))

Australia 3665
Austria 3862
Belgium 3710
Brazil 3288
Canada 5923
China 3652
Denmark 2358
Finland 3409
France 5779
Germany 5397
Italy 4018
Japan 5359
Korea 3399
Mexico 3845
Netherlands 4199
Singapore 3443
Spain 3557
Sweden 2925
Switzerland 4103
United Kingdom 5102
United States 7482

In [123]:
for country, country_data in groups:
    print(country, len(country_data))
    print(type(country), type(country_data))

Australia 3665
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Austria 3862
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Belgium 3710
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Brazil 3288
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Canada 5923
<class 'str'> <class 'pandas.core.frame.DataFrame'>
China 3652
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Denmark 2358
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Finland 3409
<class 'str'> <class 'pandas.core.frame.DataFrame'>
France 5779
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Germany 5397
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Italy 4018
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Japan 5359
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Korea 3399
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Mexico 3845
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Netherlands 4199
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Singapore 3443
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Spain 3557
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Sweden 2925
<class 'str'> <class 'pandas.core.frame.DataFrame'>
Switzerland 4103
<class 'str'> <class 'pandas.core.frame.DataFrame'>
United Kingdom 5102
<class 'str'> <class 'pandas.core.frame.DataFrame'>
United States 7482
<class 'str'> <class 'pandas.core.frame.DataFrame'>

In [121]:
for country, country_data in groups:
    print(
        country,
        country_data['Revenue'].max() - country_data.Revenue.min(),
        sep='\t'
    )

Australia	516135.14
Austria	321202.98
Belgium	310499.39
Brazil	352749.39
Canada	648467.6
China	1058301.46
Denmark	313721.1
Finland	770549.32
France	472225.66
Germany	566579.2
Italy	487457.3
Japan	686566.27
Korea	580965.0
Mexico	464070.9
Netherlands	506648.03
Singapore	556619.8
Spain	482286.38
Sweden	295462.2
Switzerland	267702.42
United Kingdom	605546.68
United States	1635687.96

In [122]:
for country, country_data in groups:
    print(
        country,
        country_data['Revenue'].max(),
        country_data['Revenue'].idxmax(),  # do you remember the idxmax() from Series lessons?
        sep='\t'
    )

Australia	516135.14	70573
Austria	321202.98	82615
Belgium	310499.39	49613
Brazil	352749.39	44350
Canada	648467.6	76609
China	1058301.46	70217
Denmark	313721.1	63555
Finland	770549.32	80129
France	472225.66	80530
Germany	566579.2	81240
Italy	487457.3	66622
Japan	686566.27	44802
Korea	580965.0	62036
Mexico	464070.9	68672
Netherlands	506648.03	46489
Singapore	556619.8	61696
Spain	482286.38	75501
Sweden	295462.2	79730
Switzerland	267702.42	48559
United Kingdom	605546.68	15898
United States	1635687.96	67651

In [127]:
for country, country_data in groups:
    print(
        country,
        country_data['Revenue'].max(),
        country_data['Revenue'].idxmax(),
        country_data.loc[country_data['Revenue'].idxmax()],
        '\n'*2,
        sep='\t'
    )

Australia	516135.14	70573	Retailer country                        Australia
Order method type                             Web
Retailer type                           Golf Shop
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2014
Quarter                                   Q1 2014
Revenue                                 516135.14
Quantity                                      439
Gross margin                              0.48694
Name: 70573, dtype: object


Austria	321202.98	82615	Retailer country                          Austria
Order method type                             Web
Retailer type                           Golf Shop
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2014
Quarter                                   Q2 2014
Revenue                                 321202.98
Quantity                                      266
Gross margin                             0.487383
Name: 82615, dtype: object


Belgium	310499.39	49613	Retailer country               Belgium
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2013
Quarter                        Q2 2013
Revenue                      310499.39
Quantity                           877
Gross margin                  0.293879
Name: 49613, dtype: object


Brazil	352749.39	44350	Retailer country                Brazil
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2013
Quarter                        Q2 2013
Revenue                      352749.39
Quantity                           996
Gross margin                  0.294116
Name: 44350, dtype: object


Canada	648467.6	76609	Retailer country                Canada
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2014
Quarter                        Q2 2014
Revenue                       648467.6
Quantity                          1172
Gross margin                  0.290493
Name: 76609, dtype: object


China	1058301.46	70217	Retailer country                            China
Order method type                             Web
Retailer type                           Golf Shop
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2014
Quarter                                   Q1 2014
Revenue                                1058301.46
Quantity                                      906
Gross margin                             0.486517
Name: 70217, dtype: object


Denmark	313721.1	63555	Retailer country               Denmark
Order method type                  Web
Retailer type          Warehouse Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2013
Quarter                        Q4 2013
Revenue                       313721.1
Quantity                           567
Gross margin                  0.290493
Name: 63555, dtype: object


Finland	770549.32	80129	Retailer country               Finland
Order method type                  Web
Retailer type            Outdoors Shop
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2014
Quarter                        Q2 2014
Revenue                      770549.32
Quantity                          2165
Gross margin                  0.297579
Name: 80129, dtype: object


France	472225.66	80530	Retailer country                France
Order method type                  Web
Retailer type            Outdoors Shop
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2014
Quarter                        Q2 2014
Revenue                      472225.66
Quantity                          1343
Gross margin                  0.289005
Name: 80530, dtype: object


Germany	566579.2	81240	Retailer country               Germany
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2014
Quarter                        Q2 2014
Revenue                       566579.2
Quantity                          1024
Gross margin                  0.290493
Name: 81240, dtype: object


Italy	487457.3	66622	Retailer country                 Italy
Order method type                  Web
Retailer type          Warehouse Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2013
Quarter                        Q4 2013
Revenue                       487457.3
Quantity                           881
Gross margin                  0.290493
Name: 66622, dtype: object


Japan	686566.27	44802	Retailer country                 Japan
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2013
Quarter                        Q2 2013
Revenue                      686566.27
Quantity                          1946
Gross margin                  0.291401
Name: 44802, dtype: object


Korea	580965.0	62036	Retailer country                 Korea
Order method type                  Web
Retailer type          Warehouse Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2013
Quarter                        Q4 2013
Revenue                       580965.0
Quantity                          1050
Gross margin                  0.290493
Name: 62036, dtype: object


Mexico	464070.9	68672	Retailer country                           Mexico
Order method type                             Web
Retailer type                        Sports Store
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2014
Quarter                                   Q1 2014
Revenue                                  464070.9
Quantity                                      402
Gross margin                             0.486202
Name: 68672, dtype: object


Netherlands	506648.03	46489	Retailer country           Netherlands
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2013
Quarter                        Q2 2013
Revenue                      506648.03
Quantity                          1432
Gross margin                  0.293395
Name: 46489, dtype: object


Singapore	556619.8	61696	Retailer country             Singapore
Order method type                  Web
Retailer type          Warehouse Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2013
Quarter                        Q4 2013
Revenue                       556619.8
Quantity                          1006
Gross margin                  0.290493
Name: 61696, dtype: object


Spain	482286.38	75501	Retailer country                            Spain
Order method type                             Web
Retailer type                        Sports Store
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2014
Quarter                                   Q1 2014
Revenue                                 482286.38
Quantity                                      409
Gross margin                             0.487061
Name: 75501, dtype: object


Sweden	295462.2	79730	Retailer country                Sweden
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                   Star Gazer 2
Year                              2014
Quarter                        Q2 2014
Revenue                       295462.2
Quantity                           534
Gross margin                  0.290493
Name: 79730, dtype: object


Switzerland	267702.42	48559	Retailer country                      Switzerland
Order method type                             Web
Retailer type                           Golf Shop
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2013
Quarter                                   Q2 2013
Revenue                                 267702.42
Quantity                                      227
Gross margin                             0.499394
Name: 48559, dtype: object


United Kingdom	605546.68	15898	Retailer country        United Kingdom
Order method type                  Web
Retailer type             Sports Store
Product line         Camping Equipment
Product type                     Tents
Product                      Star Lite
Year                              2012
Quarter                        Q2 2012
Revenue                      605546.68
Quantity                          1658
Gross margin                  0.315495
Name: 15898, dtype: object


United States	1635687.96	67651	Retailer country                    United States
Order method type                             Web
Retailer type                        Sports Store
Product line                       Golf Equipment
Product type                                Woods
Product              Hailstorm Titanium Woods Set
Year                                         2014
Quarter                                   Q1 2014
Revenue                                1635687.96
Quantity                                     1416
Gross margin                             0.486219
Name: 67651, dtype: object

### A new data frame and adding to its the biggest rows

In [130]:
the_biggest_revenues = pd.DataFrame()
for country, country_data in groups:
    the_biggest_revenues = the_biggest_revenues.append(  # strange adding: val = val.append(..)
        country_data.loc[country_data['Revenue'].idxmax()]
    )
the_biggest_revenues.head()

,Gross margin,Order method type,Product,Product line,Product type,Quantity,Quarter,Retailer country,Retailer type,Revenue,Year
70573,0.486940,Web,Hailstorm Titanium Woods Set,Golf Equipment,Woods,439.0,Q1 2014,Australia,Golf Shop,516135.14,2014.0
82615,0.487383,Web,Hailstorm Titanium Woods Set,Golf Equipment,Woods,266.0,Q2 2014,Austria,Golf Shop,321202.98,2014.0
49613,0.293879,Web,Star Lite,Camping Equipment,Tents,877.0,Q2 2013,Belgium,Sports Store,310499.39,2013.0
44350,0.294116,Web,Star Lite,Camping Equipment,Tents,996.0,Q2 2013,Brazil,Sports Store,352749.39,2013.0
76609,0.290493,Web,Star Gazer 2,Camping Equipment,Tents,1172.0,Q2 2014,Canada,Sports Store,648467.60,2014.0

In [132]:
products.nlargest(1, 'Revenue')  # an upgrade?

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
67651,United States,Web,Sports Store,Golf Equipment,Woods,Hailstorm Titanium Woods Set,2014,Q1 2014,1635687.96,1416,0.486219

In [133]:
# upraded
the_biggest_revenues = pd.DataFrame()
for country, country_data in groups:
    the_biggest_revenues = the_biggest_revenues.append(  # strange adding: val = val.append(..)
        country_data.nlargest(n=1, columns='Revenue')
    )
the_biggest_revenues.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
70573,Australia,Web,Golf Shop,Golf Equipment,Woods,Hailstorm Titanium Woods Set,2014,Q1 2014,516135.14,439,0.486940
82615,Austria,Web,Golf Shop,Golf Equipment,Woods,Hailstorm Titanium Woods Set,2014,Q2 2014,321202.98,266,0.487383
49613,Belgium,Web,Sports Store,Camping Equipment,Tents,Star Lite,2013,Q2 2013,310499.39,877,0.293879
44350,Brazil,Web,Sports Store,Camping Equipment,Tents,Star Lite,2013,Q2 2013,352749.39,996,0.294116
76609,Canada,Web,Sports Store,Camping Equipment,Tents,Star Gazer 2,2014,Q2 2014,648467.60,1172,0.290493